VowpalWabbit/vowpal_wabbit

- vowpalwabbit/lrq.cc
bugfix: lrq should not always use dropout for testing.
> lrq arg bugfix

- explore/static/MWTExplorer.h
We could use sprintf here instead, but the simpler fix of using “unsigned long long” seems to be working. This previously fixed to_string errors in cbify.cc as well.
> fixed to_string errors for MwtExplorer.h

- vowpalwabbit/lda_core.cc
- vowpalwabbit/vw.sln
remove clashing redefinition of fmax and fmin. This causes a build error
change configuration of explore to x64 to avoid incompatible project errors
> remove classhing redefinition of fmax and fmin

- vowpalwabbit/gd.cc
- vowpalwabbit/lrq.cc
DO NOT MERGE, there is still something that is not right.  Allow me to explain.
This code was a hot mess.  First, the fixes:
* gd.cc tries to access audit data even when all.audit=false
* lrq.cc crazy unsafe and unreadable string manipulations replaced with stringstream
* lrq.cc to tell core not to audit/invert_hash if iter>0
* audit data memory leaked fixed
Ok now the problem.  Audit works great:
./vw  --lrq wc1 z --audit
...
w^main:216796:1:0@0     c^foo:53090:1:0@0       lrq^c^foo^1:53091:0.389678:0@0     Constant:232120:1:0@0
...
However invert_hash doesn't print human readable stuff, except for Constant:
./vw  --lrq wc1 z --invert_hash foo; cat foo
...
Version 7.8.0
Min label:0.000000
Max label:1.000000
bits:18
0 pairs: 
0 triples: 
lda:0
0 ngram: 
0 skip: 
options: --lrq wc1
:0 …
> lrq audit bugfixes

- vowpalwabbit/vw_static.vcxproj
This will prevent the warnings for using MS deprecated  Winsock functions.
Note that _CRT_SECURE_NO_WARNINGS which turns off the printf warnings has already been inserted by some other prior check in. I have left it in.
> add _WINSOCK_DEPRECATED_NO_WARNINGS to vw_static project

- vowpalwabbit/parse_primitives.h
Fix for *Is parseFloat() too cautious?* from
https://github.com/JohnLangford/vowpal_wabbit/issues/510
Copy of original report:
I suspect that `strtod()` is unnecessary called in `parseFloat()` in `parse_primitives.h` in case the float ends with a new line bcs of
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_primitives.h#L96
``if (*p == ' ')//easy case succeeded.``
Perhaps it's better to use
``if (*p == ' ' || *p == '\n')//easy case succeeded.``
I would also include `'\t'` as it's default separator when you join two files with Unix *paste* command
> Fix for *parseFloat() is too cautious* (11)

- vowpalwabbit/parse_args.cc
Fixing help for initial_weight as described in 14 of
https://github.com/JohnLangford/vowpal_wabbit/issues/510
Copy of original bug report
The help line for initial_weight says:
``--initial_weight arg              Set all weights to an initial value of 1.``
Shall " be to an initial value of **arg**." I suppose.
> fix for typo in initial_weight help (14)

- vowpalwabbit/parse_regressor.cc
Fix for https://github.com/JohnLangford/vowpal_wabbit/issues/510
*if* clauses are reordered and *else* are added between them.
The copy of original bug report is:
In `initialize_regressor()` in `parse_regerssor.cc` it's worth adding else between these blocks
```
if (all.random_weights)
{...}
if (all.random_positive_weights)
{...}
if (all.initial_weight != 0.)
{...}
```
The `random_positive_weights` is set to true automatically with `--new_mf` mode in `mf.cc`. I found that these random values ( `0.1 * frand48()` ) are too big for my dataset (9000 features per example). So I initialised regressor with help of `--initial_weight` with something like 1e-5 and got better convergence. But now regressor initialises twice. I would put *else* clauses between these 3 *if*'s and reorder them so …
> Multiple regressor initialisation fix (12)

- vowpalwabbit/allreduce.cc
- vowpalwabbit/parser.cc
In our test and production environments we see server slots in use by clients that have long disappeared (by normal program termination). Somehow the TCP connections are not properly closed and the TCP connection on the server remains in an ESTABLISHED state. 
If TCP keepalive is enabled these stale connection slots will be reused, preventing the need for a vw restart.
> Enable TCP KeepAlive

- vowpalwabbit/global_data.h
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_example.cc
According to https://github.com/JohnLangford/vowpal_wabbit/issues/510
This pull request contains implementation of --redefine param.
Original proposal:
The first thing I have implemented in my VW fork is *--redefine* parameter which allows me to rename any namespace or set of namespaces. I gave  a new namespaces to each feature of original dataset taking their names were from [a-Z] interval. Then I declared a parameter *--redefine* which takes string argument in form of *x:=n* where *x* is a list of old namespaces, *:=* is an operator and *n* is a new namespace to which they should be assigned. That allowed me to put something like following in my vw command line:
``--redefine abcdefgihjklmnoprstquwz:=L --redefine abcdegf:=a --ignore L  --q aa``
In example above we assign all our …
> Redefine namespace param implementation (1)

- vowpalwabbit/gd.cc
- vowpalwabbit/kernel_svm.cc
- vowpalwabbit/lda_core.cc
Consolidate SIMD used in gd.cc to unify the different implementations of inverse square root. Add ARM NEON implementation.
Rename: VW_LDA_NO_SSE2 -> VW_NO_INLINE_SIMD (i.e., -DVW_NO_INLINE_SIMD on the compiler's command line to disable SIMD, SSE2 or NEON).
NOTE: "static inline" tells g++ and clang++ that InvSqrt() is a leaf function, so it can be aggressively inlined.
> arm_neon_simd

- vowpalwabbit/cache.cc
- vowpalwabbit/multiclass.cc
- vowpalwabbit/simple_label.cc
Don't assume x86-like lax alignment or bus errors occur. Use memcpy() to
ensure unaligned data is copied correctly on all platforms. (Found on ARM).
> assume_stricter_alignment

- vowpalwabbit/cb_algs.cc
- vowpalwabbit/cost_sensitive.cc
- vowpalwabbit/global_data.h
- vowpalwabbit/main.cc
- vowpalwabbit/multiclass.cc
- vowpalwabbit/simple_label.cc
Remove some vestiges of C printf formatting. Reduces warnings on non-x86
platforms, like ARM, where size_t isn't necessarily unsigned long and formatting
warnings are enabled.
> prefer_cxx_io

- utl/vw-hypersearch
- vowpalwabbit/active.cc
- vowpalwabbit/bs.cc
- vowpalwabbit/csoaa.cc
- vowpalwabbit/global_data.cc
- vowpalwabbit/topk.cc
Was missing so vw barfs when presented with a floating point numbers inside --affix args.
Also unrelated enhancement for cryptic "write error" cases (just has a bunch of these in daemon mode which makes it hard to figure out root cause).
> utl/vw-hypersearch: add --affix to options accepting integer-only

- explore/static/MWTExplorer.h
- vowpalwabbit/cbify.cc
Clean up after clang++ warnings (and gcc 4.7+ too!) about needing virtual destructors in derived classes. Without the virtual dtors, gcc 4.7 warns about undefined behavior... but it's just good practice and eliminates the warnings. clang++, OTOH, just warns about needing virtual dtors.
> cbify.cc/MWTExplorer.h -- minimally required virtual destructors.

- configure.ac
- vowpalwabbit/gd.cc
- vowpalwabbit/gd.h
- vowpalwabbit/global_data.h
- vowpalwabbit/parse_regressor.cc
Few notes on this one (9): https://github.com/JohnLangford/vowpal_wabbit/issues/510
This patch affects GD and FTRL
I found 3 problems in GD if its state is restored from save_resume model:
a). average loss is different 
b). average loss since last is different in print_update() for first outputted value
c). number of examples per pass is wrong in vw' s summary
a) could be fixed by restoring `g.total_weight value`, b) - by restoring `sd->old_weighted_examples` and c). by restoring `all.current_pass` values.
as `g` object was removed from `save_load_online_state` arguments list (bcs of its call from ftrl, suppose)I've added `g*` as an optional argument. That required `save_load_online_state()` declaration change in `gd.h` and forward declaration of `struct gd;` before it. (As `struct gd` is …
> save_resume fix 2 (9)

- README.md
- autogen.sh
- configure.ac
- vowpalwabbit/Makefile.am
Add tests for large file support, eliminating the hacky  _FILE_OFFSET_BITS=64 command line definition. Large file support is enabled on platforms where this is an option.
Disentangle profiling option from compiler optimization. Adds a new configure flag, "--enable-debug", that sets the compiler's optimization to "-g -O1". The default is the highly optimized compiler setting.
NOTE: Regenerate Makefile(s) after the pull request is merged for the default platform.
> autotools_cleanups

- Makefile
- test/daemon-test.sh
This should help those who run `make test` and fail because they are missing `library/ezexample_predict`
Also added a fix for `daemon-test.sh` based on the Fedora report where `netcat` is missing but `nc` exists.  They seem to be compatible for simple usage.
> Makefile: 'make test' depends on vw and library_example

- vowpalwabbit/lda_core.cc
[Sorry if the change set looks huge, caused in large part by running the code through clang-format to make it more readable.]
Refactor the LDA inline SIMD code into two blocks: one block for fast approximations vs. accuracy, the second block for SIMD code vs. serial code.
Update x86 SIMD code and use SSE3, SSE4.2 intrinsics, if the compiler has them enabled. Vector element extraction is template code with a specialization for the 0'th element. All of this results in better instruction selection in clang, gcc. [GCC 4.6.2 supports SSE4.1 with the "-msse4.1" flag. Not sure if this is desired in the Travis builds.]
Also prefer STL algorithms in a few places where they make sense, show examples of how C++ lambdas work (it's a C++0x feature.)
> lda_core.cc SIMD refactoring

- utl/vw-convergence
- utl/vw-hypersearch
The important change is adding a `-e script [args...]` hook to `vw-hypersearch` so users can plug-in arbitrary model goodness evaluation functions rather than the default average loss from `vw`.   This already helped me a lot to move much faster forward in a Kaggle competition.  e.g. You may wrap KDD `perf` on independent test sets, use various AUCs etc.
The other is miscellaneous enhancements to vw-convergence.  Thanks.
> improvements to utl vw-convergence and vw-hypersearch

- java/src/main/c++/vw_VWScorer.cc
During a performance test, a memory leak was discovered in the JNI layer.  This is to fix the string deallocation issue that wasn't done in the original JNI implementation here at eHarmony.
> Deallocate string memory and local reference in JNI layer

- test/RunTests
- vowpalwabbit/ftrl.cc
The documentation suggests to use the `--ftrl` flag in order to use the FTRL-proximal update rule. I noticed that the flag that was actually supported is `--ftrl_proximal`. I also noticed that there have been a couple of name changes from *ftrl_proximal* to *ftrl* in the code base. So, assuming that you'd want to extend this to the actual command line arguments, I updated those as well. (Conversely, you might want to change `--ftrl` to `--ftrl_proximal` in the docs.)
> renamed --ftrl_proximal to --ftrl for consistence with documentation

- test/train-sets/ref/lda-2pass-hang.stderr
- test/train-sets/ref/wiki1K.stderr
- vowpalwabbit/lda_core.cc
- vowpalwabbit/vw_static.vcxproj
a) Fixes a bug in lda where predictions from a saved model do not match with final predictions during training.
In its current state, the model was doing an M-step during prediction where as only an E-step is requried to get the per-document topic prediction.
b) During the E-step lda_alpha parameter is required but is not serialized as part of the regressor. It is added to the --file_options to persist.
c) Fixing windows visual studio build breakage caused by --ftrl_proximal -> ftrl changes.
Illustration of bug(a)
----------------------
During training
.\vw --lda 7 --lda_rho 0.1 --lda_alpha 10 --lda_D 1000 --minibatch 32 --initial_t 100 --power_t 0.5 --passes 10 -b 12 --cache_file lda.cache -f lda.model -d .\ohsumed.train.vw -k --readable_model lda.readable.model -l 0.01 --lda_epsilon …
> Fixes three separate bugs

- vowpalwabbit/parse_args.cc
( unsigned char iterate counter doesn't terminate)
This fixes a bug introduced in eliminated a Visual Studio warning.
> Fix #574 redefine functionality is broken

- R/dt2vw.R
Hi everyone,
We're a team of two data scientists working at AXA Global P&C, trying to create an interface between R and VW to compute fast and fully functional GLMs (Generalized Linear Models). Although a GLM package already exists in R, it rapidly shows its limits with large databases ; a problem that could be solved using VW's fast out-of-core learning capabilities. 
As a starting point, we developed a script to convert R datatables to the VW data format. It utilizes the data.table package optimized routines for fast conversion, and deals with potential format problems (e.g usage of VW special characters in the variable names)
We'd like to opensource our code as it could be useful to other R-VW users, and we were wondering if we could directly contribute to the Vowpal Wabbit repository. …
> R to vw data conversion

- cs_test/VowpalWabbitInterface.cs
- vowpalwabbit/parse_regressor.cc
- vowpalwabbit/vw.h
- vowpalwabbit/vwdll.cpp
- vowpalwabbit/vwdll.h
Add a way for saving model at any moment. This is needed when the input
format method does not apply. The input method requires example goes
through generic_driver().
> add API to save model

- utl/vw-hypersearch
I think this will really help issue https://github.com/JohnLangford/vowpal_wabbit/issues/616
> utl/vw-hypersearch: I'm told on Windows PATH separator is ';'

- vowpalwabbit/gd.cc
This should resolve #648 
Currently `[n]` postfix is added to feature names in inv_hash mode if offset is > 0.
That means in oaa features for classes > 1 will get `[n]` postfix.
I couldn't think out a good way to distinguish cases when `offset` isn't used by learning algo (without additional global variables), thus postfix [1] isn't printed for oaa && `offset == 0`
Example output for `echo -e '3 |f a b c\n2 |f a b c' | vw --oaa 3 -q ff --invert_hash=model.invert`:
```
Constant:202096:-0.132257
Constant[2]:202096:-0.132257
Constant[3]:202096:-0.132257
f^a:57420:-0.132257
f^a*f^b:123444:-0.132257
f^a*f^b[2]:123445:0.014981
f^a*f^b[3]:123446:-0.014981
f^a*f^c:157988:-0.132257
f^a*f^c[2]:157989:0.014981
f^a*f^c[3]:157990:-0.014981
f^a[2]:57420:-0.132257
f^a[3]:57420:-0.132257 …
```
> inv_hash fix for oaa

- vowpalwabbit/interactions.h
- vowpalwabbit/parse_args.cc
should resolve #649
Wildcard now includes default namespace.
--redefine functionality was adjusted to new interpretation of a wildcard.
Only one line was changed: in interactions.h
And 3 deleted from parse_args.cc
Changes reported in seed_vw_model are due to move of lines in parse.cc - no any changes in these functions were made.
> default ns now a part of  wildcard

- vowpalwabbit/interactions.cc
With help of valgrind and `-fmudflap` i've found a bug in my own module. It's in function that evaluates 
count of generated features and sum of their squared weights. It didn't affect its results.
It seems sometimes I can compare last element of v_array with v_array->end in a loop like
`for(i; i < arr->end;++i) compare(i, i+1)`
And accessing data of v_array->end is dangerous.
On practice that didn't cause any problems as (v_array->end-1 != v_array->end) with high probability. So I wouldn't notice it without valgrind.
Correctness of function output is checked by testing with enabled DEBUG_EVAL_COUNT_OF_GEN_FT
> fixing illegal memory access in generated features count evaluation func

- vowpalwabbit/gd.cc
First commit for:
```
1) For the non-interaction terms, the value of the first class's coefficient is repeated for each subsequent class. Using Martin's short example, "echo -e '3 |f a b c\n2 |f a b c' | vw --oaa 3 -q ff --invert_hash=model.invert", the invert_hash output and readable_model output for feature "c" are:
f^c:228992:-0.132257
f^c[1]:228992:-0.132257
f^c[2]:228992:-0.132257
228992:-0.132257
228993:0.014981
228994:-0.014981
The quadratic terms match between invert_hash and readable_model.
```
I forgot to add offset to feature weight in case of single feature audit.
Perhaps we'll need some make tests at least for audit/inv_hash after all bugs will be fixed.
> multiple fixes for oaa

- R/dt2vw.R
When namespace is null and a weight is specified, the weight is pasted as a continuous variable.
> fixes bug getting feature names when namespace is null

- Makefile
Currently there is a bug in the makefile that prevents us from building pyvw correctly
on mac os.
The problem is that BOOST_LIBRARY is set to "-L /usr/lib -L /usr/local/lib"
which is a problem because there is a libpython in /usr/lib that is not the one used to
compile boost, and that libpython hides the one in /usr/local/lib, which is the one we want.
The solution is to set BOOST_LIBRARY to "-L /usr/local/lib" so that the correct
libpython can be found.
> fix bug on Makefile for mac

- vowpalwabbit/interactions.cc
Thanks to Stephen Hoover I've identified a bug in my duplicate interactions filtering code. That piece of code is executed by default and leads to segfault on Mac OS if there are more than 1 interaction specified (or wildcard is used). Unluckily, it wasn't lead to crash on Ubuntu, so I've missed it. Most probably Win isn't affected too.
The problem was caused by violation of [strict ordering rule](http://stackoverflow.com/questions/979759/operator-and-strict-weak-ordering/981299#981299) in custom function passed to `std::sort()`
> fix -q :: segfault for mac os

- vowpalwabbit/parse_regressor.cc
This commit should fix model files compatibility broken in 7.9. It was broken at [this](https://github.com/JohnLangford/vowpal_wabbit/commit/c316ebe62a2a428ab13841195bf7dc5420f5a1db) commit.
just before 7.8 got tag 7.9. The problem is that `all.rank` field was removed from `vw` class and was excluded from saving in model header.
If we read dummy `uint32` at this point - at least simple 7.8 model could be successfully read in 7.10.2
Current solution reads dummy 32bit at place where rank was stored in model files with version <= 7.8.
Note: in case read value != 0 the warning is displayed. The user is asked to pass this value manually via command line.
> fix vw[<=7.8] model file compatibility

- vowpalwabbit/parse_regressor.cc
Addition to #676 
In case rank: N is found in old model file and N != 0 vw will check if any --rank M was specified in command line. If it's not - it will add --rank N to it. `gd_mf_setup` with `missing_options` is called later so it will process parameter as usual.
If there is already --rank M in command line it just warns the user. I decided not to overwrite command line value. Frankly, vw will crash if N != M anyway.
> better old model files rank processing

- test/daemon-test.sh
- utl/csv2vw
Hi John,
I've seen attempts at converting csv to vw format in the past, but all of them fell short in one way or  another, so I finally wrote my own that does everything I needed correctly. I found it very useful in a recent Kaggle competition.
This new utility supports:
- Optionally use header line for feature names (`-h` option)
- If no  `-h` is used, will number features as `1..k` based on column number
- Multiclass labels will be auto-converted to `1..k` if they are non-numeric e.g. `species: setosa,versicolor,virginica`
- Categorical features are auto-converted to vw boolean `name=value`
- Numerical features will use name:value
- Numeric command-line arg allows specifiying the label column number (also: negative numbers conveniently support "from end of line" e.g: -1 is last column) …
> New utility: utl/csv2vw: better CSV/TSV to vw converter

- test/daemon-test.sh
When using autoconf/libtool `vw` may be wrapped and appear as `.../.libs/lt-vw` - this causes `stop_deamon()` to fail to kill the process properly.
This pull-request solves issue https://github.com/JohnLangford/vowpal_wabbit/issues/680 (Test 61 failure) reported by Alex.
> daemon-test.sh: make stop_daemon() work nicely with libtool

- vowpalwabbit/interactions.cc
- vowpalwabbit/interactions.h
Switched to faster implementation of C(n,k) as proposed by Martin.
C(n,k) is used in estimation of number of generated features for interacting namespaces that called once for each example in parser.cc.
Resolves #703
> faster C(n,k) for interactions number estimator

- vowpalwabbit/interactions.cc
Compilation on 32bit systems (and g++ 4.6.3) was broken:
interactions.cc:301:116: error: narrowing conversion of ‘2432902008176640000ll’
from ‘long long int’ to ‘size_t {aka unsigned int}’
According to C99, 7.18.4, limit of size_t is (at least) 65535.
Relying on anything bigger is implementation-specific.
> size_t on 32bit systems cannot be so high

- vowpalwabbit/search.cc
fixed bug that caused the following error in macosx 10.9.5
```
Process:         Python [15981]
Path:            /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:      Python
Version:         2.7.10 (2.7.10)
Code Type:       X86-64 (Native)
Parent Process:  bash [13731]
Responsible:     iTerm [13726]
User ID:         502
Date/Time:       2015-06-25 22:57:08.365 -0700
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  373B542D-52A6-CDE6-C399-AF9A7258BD83
Sleep/Wake UUID: 34A2697A-730F-474E-A5D4-50CDAD13240D
Crashed Thread:  0  Dispatch queue: com.apple.main-thread
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Application Specific …
```
> fixed bug in cached_action_store_or_find()

- python/Learning_to_Search.ipynb
Deleted unused variable in SequenceLabeler example in the Learning_to_Search
notebook. This variable causes the following NameError:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/Users/marcov/repos/vowpal_wabbit/python/pyvw.pyc in run()
20         self._output = None
21         self.bogus_example.set_test_only(isTest)
---> 22         def run(): self._output = self._run(my_example)
23         setup = None
24         takedown = None
<ipython-input-3-12f679e00325> in _run(self, sentence)
13             pos,word = sentence[n]
14             # use "with...as..." to guarantee that the example is finished properly
---> 15             with self.vw.example({'w': [word], 'p': [prev_word]}) …
```
> delete unused variable in example

- .travis.yml
- Makefile
- README.md
Added 3 new make targets:
vw_gcov, library_example_gcov, test_gcov which build vw and the examples with GCOV support, then run tests.  This allows coveralls to analyze test coverage in the source code, but slows the tests down signifigantly.  I also edited the travis .yml file to upload the results to coveralls.io and added the badge to the readme.
Someone will need to setup a coveralls account for the main VW project and point the badge in the readme to that badge.  Currently the coveralls badge points only to my fork.
> Try coveralls

- vowpalwabbit/lda_core.cc
- vowpalwabbit/parse_regressor.cc
Remove duplication specification of --lda in test model. It is already persisted as "lda:x" during serialization
Training predictions:
.\vw.exe -k -f lda.model -p predictions.wiki.train --initial_t 0 --power_t 0.5 -d ..\..\..\test\train-sets\wiki256.dat --lda 10 --lda_rho 1 --lda_alpha 10 --lda_D 256 --lda_epsilon 0.000100 -l 0.1 -b 8
https://gist.github.com/sharatsc/a88f60d6ed08479a5172
Testing predictions with master:
.\vw.exe -k -i lda.model -p predictions.wiki.test.wo.alpha.rho -d ..\..\..\test\train-sets\wiki256.dat --lda_epsilon 0.000100 -t
https://gist.github.com/sharatsc/73884a2dc4d2ea22ec25
Testing predictions with master where lda_alpha and lda_rho are explicitly specified:
.\vw.exe -k -i lda.model -p predictions.wiki.test -d ..\..\..\test\train-sets\wiki256.dat --lda_epsilon …
> Persist lda_alpha, lda_rho along with the model.

- utl/vw-hypersearch
Previously it did not work unless 'command' is found the current directory:
master ~/work/vowpal_wabbit $ utl/vw-hypersearch -e 'cat utl/vw-hypersearch' 0 1 echo %
-e cat utl/vw-hypersearch: No such file or directory
Usage: vw-hypersearch [options] <lower_bound> <upper_bound> [tolerance] vw-command...
...
With this patch it works fine:
master ~/work/vowpal_wabbit $ utl/vw-hypersearch -e 'cat utl/vw-hypersearch' 0 1 echo %
Using external evaluation plug-in: 'cat utl/vw-hypersearch'
trying 0.618033988749895 . 1 (best)
...
> fix vw-hypersearch -e 'command argument'

- vowpalwabbit/gd.cc
I noticed a segfault when using --ftrl/--pistol and --save_resume stemming from g being NULL in save_load_online_state.
I added a null check to enter the (!adaptive && !normalized) block when g is NULL, and `vw --ftrl -i 1000lines.model -f 1000lines.model --save_resume 1000lines` now doesn't segfault, and produces a lower average loss each time it is run, indicating that things are working.
I'm new to this codebase, so it's not clear to me whether this is the right fix. Would appreciate your feedback.
> Assume adaptive and normalized are off when g is NULL

- .gitignore
- .travis.yml
- MANIFEST.in
- setup.cfg
- setup.py
Initial setup.py that creates a pip installable package for Vowpal Wabbit.
Currently the Python module is statically linked with Vowpal Wabbit.
It would be very nice if we would be able to build the Python module and have it link to the installed libvw.so as well in the future. (result being a ```pyvw``` package that works like the ```pyzmq``` package, using the system libvw.so if available otherwise building it from source)
> python pip installable vowpal wabbit package

- cluster/spark/VwSparkCluster.scala
This is a first pass at getting VW to work in cluster mode on Apache Spark.  There are a number of tricks in here (some that require insight into how the Spark engine works) that make this work.  I've seen it work on some of my data with Spark 1.2.0.  I'm not including this as a whole standalone maven project because it's meant to be template code that someone can take and do what they want with.  @deaktator if you have any comments about how this is written I'd love to hear about that.  This is written as one file because it's designed to be copy paste-able into the spark-shell with and it can be used right from there.
> Adding an example of using VW cluster mode on Apache Spark

- R/vw.R
This is a simple function to call VW from R, so far for logistic regression. Also it allows to use perf to compute the AUC on a validation set. I've found it a simple way to tune parameters based on a holdout set. I know vw has it's own methods for validation but I believe this is a common task. It's not really a new feature for VW but a simple function to facilitate validating models based on AUC. 
It's also fairly extendable to other problems.
I have written a reproducible example to show how it works. I'll add it as another file.
> call VW from R - Useful for computing AUC on validation set and parameter optimization.

- test/RunTests
This little set of changes in RunTests leaves the test directory cleaner of clutter as a result of running `make test`
> RunTests: clean-up temporary files

- vowpalwabbit/gd.cc
This refers to #726 (1)
We're switching from decimal floating point (%f) to scientific notation (%g) for coefficients in readable model to support reporting very small (<1e-6) coefficients values.
> readable_model coeffs in scientific notation

- java/src/main/java/vw/VW.java
The Java layer should build properly on Java 8 now.  The problem is that Java 8 is now much more strict on their JavaDoc requirements.  More information can be found [here](http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html).
> Fixing JavaDoc to be compatible with Java 8's fail fast mechanism

- vowpalwabbit/parse_example.cc
As discussed in #726 (2).
Was:
```
$ echo '1 |1
2 |sda:4.0fdfd:4' | ./vw
...
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
malformed example !
'|' , space or EOL expected after : "|sda:4.0"
malformed example !
'|' or EOL expected after : "|sda:4.0"
1.000000 1.000000            1            1.0   1.0000   0.0000        1
1.790589 2.581179            2            2.0   2.0000   0.3934        1
finished run
```
Proposed:
```
$ echo '1 |1                                    
2 |sda:4.0fdfd:4' | ./vw
...
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
malformed example !
'|' , space or EOL expected …
```
> better malformed ex warning

- vowpalwabbit/global_data.cc
resolves #801 
Simplest solution. Shouldn't affect performance much.
> predictions are saved as int if have no float part

- vowpalwabbit/global_data.cc
- vowpalwabbit/lrq.cc
- vowpalwabbit/lrqfa.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_args.h
resolves #808 
New platform independent format for namespace encoding is `\xAA` where AA is hex code of char.  
In bash it will be `vw -q \\xAA` as \ must be escaped.  
Note: `x` is case sensitive in `\xAA`. Just to decrease probability of accidental use.  
Change affects following vw params: q, cubic, interactions, ignore, keep, redefine, ngram, skips, lrq, lrqfa, affix, spelling.  
As a bonus --ignore and -keep now supports strings as well as single characters:
WAS: ``vw --ignore a --ignore b --ignore c --ignore d --ignore e``
NOW: ``vw --ignore abcde`` OR ``vw --ignore ab --ignore cd --ignore e``
> hex encoding of namespaces in comand line

- java/src/main/java/vw/learner/VWFloatLearner.java
- java/src/main/java/vw/learner/VWGeneric.java
- java/src/main/java/vw/learner/VWGenericBase.java
- java/src/main/java/vw/learner/VWIntLearner.java
Fix Java interface build failure due to doclint error (with Java 8),
replace IDE generated author attribution with Javadoc compatible one.
> Fix Java interface build failure due to doclint error

- .gitignore
- cluster/Makefile
- java/src/main/c++/jni_base_learner.h
It would appear that build.sh is broken.  The Centos 5 build was failing because the cluster `Makefile` now requires the boost library.  This fix will supply the boost library when linking the cluster build.
> Getting build.sh working

- test/RunTests
Turned out to be a leading space introduced by C++ FP formatting of the 1st number in a line
`RunTests` now works-around this by stripping leading white space in lenient-float compares.
> Fix recent broken build also seen in OS-X

- test/RunTests
- test/train-sets/ref/active_cover_oracular.stderr
The last line of RunTests was ignored, even if it ended with a newline,
because eof(DATA) is true in that case.
If the last line contained e.g.
train-sets/ref/active_cover_oracular.stderr
this stderr was not tested.
In this case, the file was missing, so the poor guy,
who would try to add a new test and got an error.
> Fix RunTests

- utl/vw-experiment
Vowpal Wabbit reports progressive validation loss or holdout loss by default,
but sometimes we need more:
- test/holdout loss on a given file (not on 1/10 of the training data)
This may be useful e.g. when comparing different training data sizes,
i.e. plotting the learning curve.
- train loss (to assess the amount of overfitting)
- automatic logging of experiments
- brief results (only the overall losses) on stdout,
details logged into a file
> simple Perl wrapper for measuring test loss and train loss

- Makefile.am
When installed (``make install``), the header file ``example.h`` is copied into the ``include`` directory but its dependencies aren't. Also, the header ``ezexample.h`` which provides a simpler interface is not installed. This pull request simply adds these files in ``Makefile.am``.
> install all required headers so that VW can be used as a library

- utl/vw-hyperopt.py
All functionality (and even a bit more) and almost all syntax is in the line with @martinpopel 's suggestion here: https://github.com/martinpopel/vowpal_wabbit/wiki/vw-hyperopt-plans.
See also SO questions: 
http://stackoverflow.com/questions/33262598/get-holdout-loss-in-vowpal-wabbit
http://stackoverflow.com/questions/33242742/multidimensional-hyperparameter-search-with-vw-hypersearch-in-vowpal-wabbit
Thank you @martinpopel @arielf for inspiration! I did it!
Unlike `vw-hypersearch`, `vw-hyperopt.py` can be multidimensional. It implements Tree of Parzen Estimators and Random search algorithms from `hyperopt`. TPE uses adaptive sampling strategy and addresses explore-exploit dilemma. [There is some research](http://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization.pdf) …
> Multidimensional vw hyperparameter optimization with hyperopt

- vowpalwabbit/parser.cc
Every time I get a warning about unused argument in `delete_mutex()` during linux build I'm tempted to comment `pm` out. But it'll break the code for Win32 builds. Let's just refactorize this function a little.
> Small refactorization in parser.cc::delete_mutex()

- Makefile.am
- vowpalwabbit/Makefile.am
- vowpalwabbit/example.h
- vowpalwabbit/floatbits.h
- vowpalwabbit/gd.cc
- vowpalwabbit/learner.h
- vowpalwabbit/main.cc
- vowpalwabbit/parse_args.h
- vowpalwabbit/parse_primitives.h
- vowpalwabbit/parser.cc
- vowpalwabbit/rand48.cc
- vowpalwabbit/v_array.h
- vowpalwabbit/vw.h
This is a respin of the previous pull request but using a union rather than memcpy to avoid aliasing warnings.
> Reduce warnings and enable strict aliasing (with union type punning)

- explore/static/MWTExplorer.h
- explore/static/utility.h
- vowpalwabbit/cbify.cc
- vowpalwabbit/multiclass.cc
- vowpalwabbit/vwdll.cpp
Removing all references to std::to_string to avoid build issues with other platforms (such as Cygwin). I didn't hear back from cygwin on whether there's a workaround for the "to_string not declared" error so am rewriting it using sprintf_s, which is actually faster. Linux tests ran ok, and cygwin no longer complains about this.
> removed use of std::to_string

- utl/vw-hyperopt.py
This is a follow-up to my [previous pull request](https://github.com/JohnLangford/vowpal_wabbit/pull/867). 
@arielf I worked through your suggestions, but your comment for some reason disappeared from that conversation :disappointed: Maybe it's because I re-forked the repository instead of re-syncing it.
Anyways, I made the following improvements:
* New syntax for hyperopt search space definition: one `~` symbol instead of square brackets. Now a full command looks like this:
```bash
./vw-hyperopt.py --train train_set --holdout holdout_set --max_evals 200 --outer_loss_function logistic --vw_space '--algorithms=ftrl,sgd --l2=1e-8..1e-4~LO --l1=1e-8..1e-4~LO -l=0.01..10~L --ftrl_alpha=5e-5..5e-1~L --ftrl_beta=0.01..1 --passes=1..10~I -q=SE+SZ+DR,SE~O --ignore=T~O --loss_function=logistic …
```
> Changed syntax, added plotting, small usability improvements in vw-hyperopt

- vowpalwabbit/parse_regressor.cc
resolves #831 
To reproduce the problem you may use following commands:
```
$ ./vw ../test/train-sets/rcv1_small.dat --leave_duplicate_interactions -f temp.model  -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff -q ff …
```
> dynamic buffer for file_options

- vowpalwabbit/io_buf.h
refers #876
> about confusing inconsistency in bin_text_write and bin_write. They store 0-length objects in a different way. 1st one write nothing while 2nd one write 4 zero bytes (length). 2nd approach would be better for saving empty strings (no need to store trailing 0 byte), but changing this may make models binary incompatible.
Now bin_text_write behaves as  bin_write 
the line 185 seems to be changed by my browser as I've edited the file online on github. Let me know if this is unwanted.
> sync bin_text_write and bin_write for empty obj

- vowpalwabbit/memory.h
Was previously throwing a compilation error that stderr was not defined in the call to fputs(...) on what's now line 15 and was [introduced in](https://github.com/wbt/vowpal_wabbit/blob/d1697f80fe2f174b7acd55ec64f2415632bc97df/vowpalwabbit/memory.h) version d1697f8.
> Bugfix of compilation error

- README.md
- java/src/main/bin/build.sh
- java/src/main/java/vw/jni/NativeUtils.java
closes #894 
related:  #807 #780 #822
a change to java NativeUtils class to attempt more standardized access to linux distro and version
fixes a couple bugs in build.sh
updates readme
@jmorra Build.sh passes up to the last 3 lines, where I have issues (unrelated to this PR) compiling the C code on my mac.  After some bug fixes to build.sh, VW appears to compile correctly in the linux docker images.   Could you check out this branch and try to compile it on your mac?  Or if you happen to know what's wrong in the traceback below, that would be helpful.  I wouldn't think this change should prevent VW java from working on mac, as the changes relate to linux issues, but it probably makes sense to check.
---
Some error msgs (unrelated to this PR) that I get when trying to manually compile VW on …
> java NativeUtils: lsb_release to get linux distro and version

- vowpalwabbit/memory.h
- vowpalwabbit/parse_regressor.cc
This would mark weight vector as KSM sharable:
Doing so allows to save memory if you run multiple instances of the same model in read only mode.
See more https://www.kernel.org/doc/Documentation/vm/ksm.txt
To make use of this feature you'll need to have Linux kernel >= 2.6.32 and KSM enabled
To check is KSM enabled run the command
$ grep KSM /boot/config-`uname -r`
if KSM is enabled you should see:
>> CONFIG_KSM=y
You can enable KSM with command:
$ sudo "echo 1 > /sys/kernel/mm/ksm/run"
To monitor shared pages use command:
$ grep [0123456789] /sys/kernel/mm/ksm/*
Here is an example of shared pages - two VW models (24 bits each) are shared between 14 processes. 32770 (4Kb each) unique pages_shared, pages_sharing - 425998 pages.
/sys/kernel/mm/ksm/full_scans:251 …
> Enable marking weight vector to be sharable using KSM

- cs/cli/vowpalwabbit.cpp
- cs/cli/vw_base.cpp
- cs/cli/vw_base.h
- library/ezexample_predict.cc
- library/library_example.cc
- test/train-sets/ref/ezexample_predict.stderr
- vowpalwabbit/learner.cc
- vowpalwabbit/main.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/vw.h
- vowpalwabbit/vwdll.cpp
- vowpalwabbit/vwdll.h
It turns out that init_driver never got called from the Windows side. I walked through it with John and we also simplified the code a bit. Note: generic_driver is not used when going through the C# part, as the parser is externalized there.
@trufanov-nok can you merge that into #923 and try again?
> Fixed init_driver call

- vowpalwabbit/parse_regressor.cc
When --id is not specified, we still add it to vw args as --id "", eventually this empty string is removed during the args copy in seeded model, causing the next flag to be used as --id, which is bad.
> fixed empty id being overridden in seeded model with @eisber

- Makefile.am
These headers are now required to build against the library so install them.
> Makefile.am: Install some missing header dependencies

- vowpalwabbit/global_data.h
- vowpalwabbit/parse_example.cc
fixes #983 
previously with char there were only 2 affix values possible (4 bits) per namespace
`uint32_t` could hold 8 (changed code comment)
currently 16 are available which is, I guess, more than enough.
> bugfix - namespace now stores 16 instead of just 2 affixes

- vowpalwabbit/gen_cs_example.cc
- vowpalwabbit/gen_cs_example.h
John,
This is a fix for the small bug for --cb we discussed, where if only one action is provided without cost or prob, it should be treated as only one action is eligible (and prediction should be this action). 
The problem was, when generating cost-sensitive example, when ld.costs.size() == 1, all actions are generated. This is valid for sth like 3:1:0.5 | features, but not consistent for example with test label, such as 3 | features.
So the fix is to generate all actions when (ld.costs.size() == 1 && !is_test_label(ld)). This is added for all 3 cb algorithms. 
after fix:
echo "3:1:0.5 | three
3 | three" | ./vowpalwabbit/vw --cb 5 --cb_type ips
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = 
num sources = 1
average  since …
> --cb: fix one eligible action for test sample

- vowpalwabbit/parser.cc
Just faced with a problem when VW ignores specified cache file and tries to make another one instead. It took some time to realize that this happens bcs I forgot to specify the right `-b` value during cache creation. Frankly, I didn't realized this till I debug. I think would be nice to add a few warnings for such cases if anyone else forgets how VW processes cache files.
> I few warnings for cache file processing problems

- vowpalwabbit/parser.cc
I realized that one of warnings that's triggered by exception is printed out even if there was no cache file. Like in `vw - data.vw --cache_file data.cache` when user creates cache for a first time.  In this case user gets 
```
WARNING: cache file is ignored as it can't be opened!
creating cache_file = data.cache
```
which is confusing. I don't like that.
Let's roll back this piece of code and disable this warning for now. Perhaps I'll find a time to make some cross-platform checks to separate "file not exists" from all other problems in `catch` later.
> disable one of warnings for cache file

- vowpalwabbit/global_data.cc
referring my old PR #812 
I've used `print_result()` function to output example labels and realized that it spoils `FLT_MAX` values. Looks like `sprintf(temp, "%d", (uint32_t) res)` behaves badly for very big float `res` values (which user unlikely to get on practice so it wasn't noticed). For example `FLT_MAX` is printed as `0`. 
So I suggest to use just `sprintf(temp, "%.0f", res)` instead. Looks like it provides with desired behavior and more elegant as uses same float type.
P.S. It's been a while since my last contribution to VW codebase so I may forget some nuances and I can't recall why I used float to int conversion and why I used **unsigned** int...
> Small improvement in int predictions print

- vowpalwabbit/gd.cc
When running with --audit, if an anonymous feature is present, VW will segv.
> Fix crash when running with --audit.

- test/RunTests
- test/train-sets/audit.dat
- test/train-sets/ref/audit.stderr
- test/train-sets/ref/audit.stdout
As requested, here's a test case for the --audit regression.
Also, while looking at this, I realized that the --audit output actually goes to stdout, not stderr.  Not sure if that's intended or not.
One of the issues I see is that the test case will fail if the hash function used by VW is ever changed.  I don't see a good way to template it in the current test framework.
> Test cases for --audit output.

- utl/vw-hyperopt.py
adds support for optional arguments in order to prevent the following error:
`ValueError: invalid literal for float(): -5.123953 6171_1851165462_2016-05-23_02:00:00[0.0]`
> vw-hyperopt extract label from input

- python/examples/test.py
- python/pylibvw.cc
- python/vowpalwabbit/pyvw.py
this is to fix issue #758 
there was some hacky stuff in pylibvw which erased the tag and used it to store the label type because that was needed to deallocate memory when the example was destroyed.
I couldn't find an easy way to retain the size_t labelType variable on it's own, and since example_counter was also being overridden to store this info I kept it there and used example_counter in the dealloc_example function.
this is still a bit hacky, but I didn't want to modify the base example class for this case, maybe someone has a better implementation for dealloc_example that can resolve this issue, but for now this works to get the tag.  The example counter information is still not valid, but that seems less relevant for the python library.
> retaining example tag in python lib

- README.md
- python/README.rst
At least on my machine (el capitan) `brew install boost --with-python` doesn't work. `pip install vowpalwabbit` after running that still complains about missing boost library. On the other hand, `brew install boost-python` worked.
> Update instruction for Python 2

- big_tests/Makefile
- big_tests/expected/4a/err
also make big_tests/Makefile more compatible with systems like Cygwin, which don't have lscpu by default
> Fix expected file for big_test 4a

- vowpalwabbit/array_parameters.h
- vowpalwabbit/gd_mf.cc
- vowpalwabbit/lda_core.cc
There were a few more places where `size_t` had to be replaced with `uint64_t` to fix #1086
> fix mac build

- Makefile.am
Makefile.am was missing -d so no diff was printed on failures for envs using `autogen.sh`
> Makefile.am: add -d to RunTests

- vowpalwabbit/explore_eval.cc
The policy probabilities can sometimes be > 1 with very small precision leading to unjustified violations
> consider precision

- vowpalwabbit/interactions.cc
Looks like the code that is inside `DEBUG_EVAL_COUNT_OF_GEN_FT` got outdated a bit when vw switched to 64bit address space.
These blocks are not compiled by default so it was unnoticed.
The code itself is a selfcheck for `eval_count_of_generated_ft` function. This function estimates number of features simple permutations according to some combinatorics math which is faster than just iterating throw them. And this debugging block additionally iterates throw all interactions and simple counts them and then compare with evaluated result.
> Some dubug code updated

- utl/vw-lda
`vw-lda` with the latest vw crashes with the following error:
```
transforming outputs
Exception: 'Checksum:'
Traceback (most recent call last):
File "/usr/local/bin/vw-lda", line 400, in main
vw_lda().process_args(args)
File "/usr/local/bin/vw-lda", line 252, in process_args
self.transform_outputs(args.max_terms)
File "/usr/local/bin/vw-lda", line 287, in transform_outputs
w = self.new_hash[str(word_list[0])]
KeyError: 'Checksum:
```
This PR fixes the issue by skipping past the Checksum line in the readable model.
> fix vw-lda

- vowpalwabbit/Makefile.am
Contributed by david-geiger:
Modified file:  vowpalwabbit/Makefile.am
Based on Mageia patch:
http://svnweb.mageia.org/packages/cauldron/vowpal-wabbit/current/SOURCES/vowpal_wabbit-8.2.1-linking.patch?view=markup&pathrev=1057904
Verified by me on Ubuntu.
I get a smooth build and no errors after applying the patch:
```
autogen.sh
make
make test
```
Many thanks to David (and the anonymous Mageia packager) for the fix.
> Fix to https://github.com/JohnLangford/vowpal_wabbit/issues/1107

- python/Makefile
When building in Python VirtualEnv the Makefile sets the wrong python source
This fix is a proposed solution for the issue discussed at the end of the thread to https://github.com/JohnLangford/vowpal_wabbit/issues/415
When executing
`PYTHON_LDFLAGS = $(shell python$(PYTHON_VERSION)-config --ldflags)`
in a virtual environment the Python being linked is the system Python instead of the Python in the virtual environment. As a consequence the `pylibvw.so` contains system python leading to a Segfault when trying to run
`from vowpalwabbit import pyvw`
The proposed solution is to check the `VIRTUAL_ENV` environment variable that is set when working in a virtual env. If this flag is present we use just python instead of a versioned python
> Adds a check if building within VirtualEnv

- vowpalwabbit/lda_core.cc
Hi John,
I might be missing something but it looks the new `return_example` method in lda_core.cc (bea9ce4) isn't called anywhere.
This PR replaces the calls to `return_simple_example` with `return_example` in lda_core.cc, which makes your fix for #1096 work beautifully :-)
> call return_example in lda_core.cc

- vowpalwabbit/parse_example.cc
Push audit strings into the right namespace.
Before:
$ echo "1 | aa" | ./vw -a  --quiet --affix 2
0
:13622:1:0@0    aa:37289:1:0@0  Constant:116060:1:0@0
After:
$ echo "1 | aa" | ./vw -a  --quiet --affix 2
0
affix^+2=aa:13622:1:0@0 aa:37289:1:0@0  Constant:116060:1:0@0
> fix --audit for --affix

- README.md
1) Fix: autogen.sh overwrites multiple Makefile's (not just the top one).
2) Document the clean way to restore original Makefiles.
> autogen.sh overwrites multiple Makefiles + how to restore

- python/README.rst
--with-python3 is a boost-python option:
```
> brew install boost --with-python3
Warning: boost: this formula has no --with-python3 option so it will be ignored!
...
```
```
brew info boost-python
boost-python: stable 1.63.0 (bottled), HEAD
C++ library for C++/Python interoperability
https://www.boost.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python.rb
==> Dependencies
Required: boost ✔
==> Requirements
Optional: python3 ✔
==> Options
--c++11
Build using C++11 mode
--universal
Build a universal binary
--with-python3
Build with python3 support
--without-python
Build without python 2 support
--HEAD
Install HEAD version
```
> DOC fixed install instructions for pywv

- vowpalwabbit/gd.cc
This commit fixes #1185 and allows the invert_hash to be printed in testing mode when passes > 0 and save_resume option has been used.
> Fix issue where invert_hash doesn't print parameters due to save_resume and passes > 0

- python/MANIFEST.in
- python/PACKAGE.rst
updating manifest to match new windows build files and package instructions for using twine to upload python packages
> update to python packaging to make it easier to automate process

- vowpalwabbit/nn.cc
In Neural networks, some of the hidden networks had weights but there
was no human readable string associated to the weight. This made it difficult to read in
the Human readable format because the names were clashing (All the names
for the weights into the output layer had no space_name and hence the
name was always empty). This commit adds names for these weights which
are not seen.
I believe this fixes https://github.com/JohnLangford/vowpal_wabbit/issues/1169
> nn.cc: Add human readable named for hashes

- vowpalwabbit/array_parameters.h
- vowpalwabbit/gd.cc
- vowpalwabbit/gd_mf.cc
- vowpalwabbit/lda_core.cc
- vowpalwabbit/parse_regressor.cc
resolves #1183 
The problem with GCC 6.x is described here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79508
It's a regression. In short - GCC since 5.4.1 understands only template classes in nested template list arguments while VW tries to push function pointer there. So I've just wrapped all functions in classes and make them static.
> workaround GCC 6.x compilation issue

- vowpalwabbit/parse_args.cc
My compiler is barking:
```
parse_args.cc: In function ‘const char* VW::are_features_compatible(vw&, vw&)’:
parse_args.cc:450:24: warning: self-comparison always evaluates to false [-Wtautological-compare]
if (vw1.permutations != vw1.permutations)
```
> fixing a small bug

- vowpalwabbit/interactions.h
resolves #1182 
It seems that initial code had been refactored a lot since i took a look into it last time. There was line of code missed and audit function wasn't called to pop last namespace from stack in each nested loop. I've returned it.
Also I found that much later a chunk of code containing this problem was duplicated into the code block that never executed. Apparently - it was done automatically by some code formatting tool. I deleted one of these duplicated blocks. But could only guess which one was formatted right. **Please take a note that next time you launch this tool it can reproduce this mistake again.**
> Fixing audit output for cubic features

- python/README.rst
- python/examples/sklearn_vw.ipynb
sklearn.cross_validation module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20
> do not use deprecated sklearn module

- python/pylibvw.cc
Modify `get_weighted_examples` so that `weighted_examples` is called
with no arguments.
> This fixes #1282

- vowpalwabbit/search.cc
When running in --search mode, there are *lots* of printed lines that contain
- "del_top"
- "del_example_cond"
> Removing spurious "cout" statements

- test/test-sets/ref/0099.stderr
- vowpalwabbit/gd.cc
Otherwise "vw -t" reports halved 'number of examples per pass'.
without this patch
$ vw test/train-sets/rcv1_micro.dat -f tmp.model --save_resume --quiet && vw test/train-sets/rcv1_micro.dat -i tmp.model -t 2>&1 | egrep 'number of|passes'
number of examples per pass = 5
passes used = 2
with this patch:
$ vw test/train-sets/rcv1_micro.dat -f tmp.model --save_resume --quiet && vw test/train-sets/rcv1_micro.dat -i tmp.model -t 2>&1 | egrep 'number of|passes'
number of examples per pass = 10
passes used = 1
> reset current_pass to 0 rather than 1 in test_only

- vowpalwabbit/boosting.cc
So that --raw_predictions reports that rather than score from last learner.
> boosting: set ec.partial_prediction to final_prediction

- vowpalwabbit/cbify.cc
Add support for the adf contextual bandit reduction from cbify: for each (single line) multiclass example, this generates multiline examples (one per action, then one empty example) by shifting feature indicies for each action, and reduces to cb_explore_adf instead of cb_explore.
> cbify: support adf reduction

- vowpalwabbit/cb_explore_adf.cc
This adds the --greedify option for bagging: updates happen exactly once for the
first policy in the bag (based on discussions with @JohnLangford). This seems to often help in practice.
Perhaps the option name could be improved.
I also fixed indentation in the entire function.
> cb: greedified bagging

- vowpalwabbit/baseline.cc
- vowpalwabbit/baseline.h
- vowpalwabbit/cb_adf.cc
- vowpalwabbit/cb_algs.h
- vowpalwabbit/cbify.cc
- vowpalwabbit/example.h
* parameter for lr multiplier, added automatically in cbify
* mechanism to only use baseline when manually specified in a feature. Used in DR to only use baseline for loss estimates.
cc @JohnLangford
> Baseline + cb changes

- cs/cli/vowpalwabbit.cpp
- test/RunTests
- test/save_resume_test.py
- test/train-sets/ref/hash_seed_test.stderr
- test/train-sets/ref/hash_seed_train.stderr
- vowpalwabbit/global_data.h
- vowpalwabbit/hash.h
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_example.cc
- vowpalwabbit/vw.h
When collisions are present, setting this will change the groups of features that collide.
If VW is used as a base model for ensemble classifier, setting different hash_seeds will reduce correlations.
I cleaned up hash_base static variable since I did not want there to be two places where hash seed can be set.
> add --hash_seed option

- python/tests/test_pyvw.py
- python/vowpalwabbit/pyvw.py
Currently vowpal-wabbit in cmd accepts multiple instances of the same key, for example, quadratic features could be configured thru "-q ab -q ac", on the same time it's impossible to make ```pyvw.vw(q="ab", q="ac")``` by python syntax limitation and to make ```pyvw.vw(q=["ab", "ac"])``` by the current implementation. And the only one way to do it now - mixing separate parameters with plain ```arg_str='-q ab -q ac'```.
A goal of this pull request is to make the second way of passing multi-valued keys acceptable.
> Add ability to pass a list in a python wrapper parameter, which will be translated into multiple keys

- Makefile
Necessary to compile on CentOS with a specific boost.
> Add /usr/local to BOOST_INCLUDE

- autogen.sh
This is necessary to specify a different boost on CentOS.
> Don't clobber --with-boost and --with-boost-libdir

- cs/cli/vw_arguments.h
boost throws error because underlying type in options data structure is unsigned int.
> boost cast error causing test failure

- vowpalwabbit/parse_example.cc
- vowpalwabbit/parse_primitives.h
When running in daemon mode, example parsing sometimes fails because the parser reads past the end of the example line.  These edits prevent that from happening.
> check for endLine when parsing

- python/README.rst
`--with-python3` flag isn't supported anymore for brew's `boost-python` https://stackoverflow.com/questions/48994346/installing-boost-python-for-python3-using-brew
Using flag caused me errors, but was able to install `vowpalwabbit` python package using `brew boost-python3` instead
> Update boost-python installation info

- test/RunTests
- vowpalwabbit/classweight.cc
- vowpalwabbit/parser_helper.h
Reconciling #1406   This also adds a 'keep=true' default argument to critical_vector() which we can set to 'false' so as to not keep classweight in the model file.
> Denik classweight2

- .travis.yml
- test/repeat.py
- test/test_race_condition.sh
This test repeatedly runs `vw train-sets/rcv1_small.dat --holdout_after 100` and checks if the output remains the same. It finds that sometimes vw incorrectly reports that average loss is undefined.
Second commit runs this test on travis and makes it fail there. 
```
./test_race_condition.sh
0 failed out of    2
0 failed out of    3
0 failed out of    4
0 failed out of    8
0 failed out of   16
0 failed out of   32
Output changed:
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = train-sets/rcv1_small.dat
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
1.000000 1.000000            1            1.0  -1.0000   0.0000      128 …
```
> Add a test that exposes race condition

- utl/vw-hyperopt.py
In this utility script, this part reads the holdout file and it seems like weights and tags are converted to float along with the label.
For the input `-1 0.2 1|`, this is trying to do `float("-1 0.2 1")` and thus raising a ValueError exception.
I think it's fair to consider the label only up to the first space.
> Improve some parsing in vw-hyperopt.py

- Makefile
Added check for ppc64le and removed the -msse2 option as its not supported on power. Changes have been tested.
> Support ppc64le

- python/setup.py
It looks like line 33 in this file is supposed to stop iterating through candidates whenever `find_library` returns a non-empty result. However, `exit` is not what does that. `exit` is just a Python function (see https://docs.python.org/3/library/constants.html?highlight=exit#exit) which is simply sitting there, without being called. Even if it was called, it would exit the whole process, not the loop. Please see this for details: https://gist.github.com/jaidevd/81b870dacae045faabba587b73185386
> Correctly exit loop searching for Boost libs on Linux

- README.md
Doxyfile has `HAVE_DOT` hard-coded to `YES`, which causes `command not found`
warnings when attempting to generate documentation on systems that don't have
Graphviz currently installed.
We add a clause in the corresponding section of the README that makes note of
this dependency.
> README: Mention Graphviz dependency for doc generation

- utl/vw-validate.html
LGTM.com correctly points out that there's something wrong in this JavaScript string:
https://lgtm.com/projects/g/JohnLangford/vowpal_wabbit/snapshot/cb017a413b4dc4ce9e384af8cf34744881147f21/files/utl/vw-validate.html#xb9d8c0da7aca9de8:1
This should fix the last two alerts for vowpal_wabbit's JavaScript code, so should bump up the code quality score to an A+ :slightly_smiling_face: 
(Full disclosure: I'm part of the team that build LGTM.com)
> Fix JavaScript quoting around pipe symbol in vw-validate.html (resolving LGTM.com alerts)

- reinforcement_learning/rlclientlib/live_model_impl.cc
- reinforcement_learning/rlclientlib/logger/logger.h
- reinforcement_learning/rlclientlib/utility/data_buffer.cc
- reinforcement_learning/rlclientlib/utility/data_buffer.h
- reinforcement_learning/unit_test/data_buffer_test.cc
- reinforcement_learning/unit_test/unit_test.vcxproj
- reinforcement_learning/unit_test/unit_test.vcxproj.filters
Getting rid of newlines within single request (workaround, while server-side parsing is not fixed)
> New line workaround for rlclientlib

- vowpalwabbit/cb.cc
- vowpalwabbit/gd.cc
Order of dump_interval modifications before bug fix:
1) dump_interval is initialized to 1 (see [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/global_data.cc#L270))
2) dump_interval is updated according to -P input (see [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L353))
3) If -i is present, dump_interval is updated according to dump_interval at time of model saving (see [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L854))
4) if --preserve_performance_counter is not present (see [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L917)), dump_interval is WRONGLY reset to 1 (see [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vow …
> Fixed bug causing to reset dump_interval to 1 when input model -i is provided

- appveyor.yml
Issue was introduced by installing openssl-1.1 on appveyor images which is wrongly picked up by CMake.
Workaround copied from here:
https://github.com/Microsoft/vcpkg/issues/4189#issuecomment-417462822
Fix is not released yet:
https://github.com/appveyor/ci/issues/2600
> OpenSsl linking problem workaround

- reinforcement_learning/bindings/python/test/log_test_driver.py
- reinforcement_learning/doc/python.dox
- reinforcement_learning/examples/python/basic_usage.py
- reinforcement_learning/examples/python/rl_sim.py
action_probabilities -> actions_probabilities
In rl_sim.py:
- `p` was used both for probability and person: used `person`, and `prob` now
- removed one line functions used only once (e.g., pick_a_random_person, create_context_json)
- renamed req_id to event_id
> Python Client Library: Improvements to docs

- README.md
We now need other boost parts, so the simplest is to prereq `libboost-dev`
> build instructions: program_options insufficient

- python/README.rst
- Installing `vowpalwabbit` directly with pip fails currently if boost dependencies are not installed. Updating the Readme with instructions for installing dependencies would be helpful for future users.
> Update Readme with details on installing boost dependencies

- vowpalwabbit/vw_core.vcxproj
Consuming this project from another solution requires this variable to be different
> Replace $(SolutionDir) with $(ProjectDir)

- vowpalwabbit/accumulate.cc
- vowpalwabbit/audit_regressor.cc
- vowpalwabbit/bfgs.cc
- vowpalwabbit/cache.cc
- vowpalwabbit/cb_adf.cc
- vowpalwabbit/cb_explore_adf.cc
- vowpalwabbit/classweight.cc
- vowpalwabbit/cs_active.cc
- vowpalwabbit/csoaa.cc
- vowpalwabbit/explore_eval.cc
- vowpalwabbit/gd.cc
- vowpalwabbit/global_data.h
- vowpalwabbit/interact.cc
- vowpalwabbit/kernel_svm.cc
- vowpalwabbit/learner.cc
- vowpalwabbit/lrq.cc
- vowpalwabbit/main.cc
- vowpalwabbit/oaa.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_regressor.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/parser_helper.cc
- vowpalwabbit/parser_helper.h
- vowpalwabbit/recall_tree.cc
This is required for the larger task of replacing the arguments object
> Move trace_message from arguments to vw object

- test/train-sets/ref/ksvm_train.linear.stderr
- test/train-sets/ref/ksvm_train.poly.stderr
- test/train-sets/ref/ksvm_train.rbf.stderr
- vowpalwabbit/kernel_svm.cc
When using ksvm `hinge` is forced as the loss function, but isn't recorded into the argument string. When calculating best constant later the loss function is extracted from the argument string.
> Fix best constant and best constant's loss calculation when using ksvm

- vowpalwabbit/parser.cc
When creating the json parser, the audit template parameter must be true to generate the information required by `--invert_hash`.
Fixes #1614
> Fix invert_hash with json input

- README.md
> Remove -DSTATIC_LINK_VW from Ubuntu build instructions

- .gitattributes
Adds a .gitattributes file to specify that .rc files should have UTF-16LE encoding, always.
> Fix file enocding for .rc files

- python/pylibvw.cc
- vowpalwabbit/boosting.cc
- vowpalwabbit/global_data.h
- vowpalwabbit/interactions.cc
- vowpalwabbit/interactions.h
- vowpalwabbit/parse_args.cc
Fix an issue in python bindings revealed by a warning (implicit cast from 64 to 32 bits int).
Remove usage of `long long` in favor of int64_t. The code base uses both and the later is both shorter and is more intuitive.
> Fix a small issue and cleanup usage of long long

- .pipelines/Dockerfile
This installs `clang-format` 7.0.1 (it seems to me 7.x.x is considered "stable" LLVM).
```
➜  vowpal_wabbit git:(palmerlao/update-ci-image) ✗ docker run -ti fb9f8e9fdc77 clang-format --version
clang-format version 7.0.1 (tags/RELEASE_701/final)
➜  vowpal_wabbit git:(palmerlao/update-ci-image) ✗ docker run -ti fb9f8e9fdc77 g++ --version
g++ (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
➜  vowpal_wabbit git:(palmerlao/update-ci-image) ✗ docker run -ti fb9f8e9fdc77 cmake --version
cmake version 3.2.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
> Add clang-format 7.0.1 to CI image

- .travis.yml
- Updates CI image version to 20190202.1
- This brings in changes from #1719 by @palmerlao 
- Image was built here https://vowpalwabbit.visualstudio.com/Vowpal%20Wabbit/_build/results?buildId=1083
- Image uploaded here https://hub.docker.com/r/vowpalwabbit/travis-base/tags
> Update image used in TravisCI to 20190202.1

- utl/clang-format
Turn clang-format from fail to advise.
> shift clang-format to advise

- test/repeat.py
Fixes `test_race_condition` on OSX High Sierra that comes with python 3 by default.
> [tests] Make repeat.py compatible with python 3

- test/RunTests
- test/train-sets/no_shared_features.json
This PR fixes some test issues:
* Test 175 is not enabled on Windows, because the test parser expects an empty line after the test definition.
* When enabled, the test is failing, because an empty line is missing after the example (thus failing the multi-line detection).
* Test 59 does not exist, misleading the reading of Travis logs, where the test id is not the parsed id but a counter starting from 1.
> Fix test 175

- test/train-sets/ref/topk-rec.stderr
- vowpalwabbit/topk.cc
> Convert TopK reduction to be multiline example based

- test/unit_test/CMakeLists.txt
- test/unit_test/cb_explore_adf_test.cc
- test/unit_test/explore_test.cc
- test/unit_test/main.cc
- test/unit_test/options_boost_po_test.cc
- test/unit_test/options_test.cc
- test/unit_test/stable_unique_tests.cc
Addresses one of two problems in #1745
> Do not define BOOST_TEST_DYN_LINK when statically linking

- test/unit_test/CMakeLists.txt
- test/unit_test/ccb_parser_test.cc
- test/unit_test/unit_test.vcxproj
- test/unit_test/unit_test.vcxproj.filters
- vowpalwabbit/CMakeLists.txt
- vowpalwabbit/cache.cc
- vowpalwabbit/cache.h
- vowpalwabbit/cb.cc
- vowpalwabbit/conditional_contextual_bandit.cc
- vowpalwabbit/conditional_contextual_bandit.h
- vowpalwabbit/cost_sensitive.cc
- vowpalwabbit/example.h
- vowpalwabbit/parse_primitives.cc
- vowpalwabbit/parse_primitives.h
- vowpalwabbit/vw_core.vcxproj
**This PR is to the CCB staging branch and not master**  
This PR is the same content as #1736 
* Adds label parser for CCB
* New label and prediction type
* Consolidate `substring_equal` usages
* Unit tests for ccb label parsing
[See here for a definition of the input format](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Contextual-Bandit-algorithms#conditional-contextual-bandit)
> Add CCB label parsing, label and prediction types

- CMakeLists.txt
- python/pylibvw.cc
- vowpalwabbit/vwdll.h
Release builds were not working for two reasons. First, it would always
override -DCMAKE_BUILD_TYPE with "Debug" Second, it would use CONFIG, which
is not set on OSX with cmake 3.13.1 at least.
Finally, set the default symbol visibility to hidden on unix - linux is a
misnomer in the build script... Without it, we export something like 700
extra symbols that corresponds to all public functions in VW. Exporting
them on unix means making them available to be interposed and requiring an
indirect call to be used at all call sites.
The LTO mode, which can be used with -DLTO=1, enables clang's thinlto mode.
Debug: 9.191kb
Relase+bad visibility: 3.728kb
Release+good visibility: 3.615kb (-113kb)
Release+lto+viz: 3.374kb (-354kb)
Doing `vw -c rcv1.train.raw.txt -b 22 --ngram 2 --skips 4 -l 0.25 …
> Fix build scripts forcing Debug builds. Add LTO mode and fix VW default visibility.

- test/RunTests
In the testing logs (e.g. in Travis), this shows the test label shown in the comment above each test, rather than just a counter. For instance, the logs will show 175 for the test labeled `# Test 175:`, instead of the value of the counter. This avoids weird discrepancies when reading the Travis logs.
cc @yannstad
> RunTests: use test label number instead of counter

- vowpalwabbit/global_data.cc
- vowpalwabbit/global_data.h
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_primitives.cc
- vowpalwabbit/parse_primitives.h
- vowpalwabbit/parser.cc
- vowpalwabbit/search.cc
- Migrate some usages of v_array to std:vector where possible
- Use std::stack for reduction stack
- Make tokenize templated to allow any container type
> Migrate from v_array to std::vector in some places + other changes

- vowpalwabbit/options_boost_po.cc
This fixes 1/3 of the errors in #1746.
> On OSX, we need to catch boost::program_options::ambiguous_option directly. Probably due to different boost versions.

- test/RunTests
- test/same-model-test.sh
- test/train-sets/same_model_test.0.dat
- test/train-sets/same_model_test.1.dat
- vowpalwabbit/accumulate.cc
Fix #1771 
After some investigations, I think this issue might be caused by wrong stride size when averaging the weights in `accumulate_weighted_avg`. A simple fix here might be enough.
What do you think about?
> Fix weighted average on cluster mode

- vowpalwabbit/example.h
- vowpalwabbit/gd.h
This is a very trivial change enabling interactions to be overridden by an example. I'll follow this up with an object pooled approach. However I think the opt in approach here is good as it doesn't affect existing usage perfomance wise (except for one conditional).
> [CCB] Enable interactions to be overridden by an example

- vowpalwabbit/conditional_contextual_bandit.cc
- vowpalwabbit/conditional_contextual_bandit.h
- vowpalwabbit/global_data.h
- vowpalwabbit/learner.h
- vowpalwabbit/parse_args.cc
PR description:
* add a new option `--ccb_explore_adf`, that triggers `-cb_explore_adf` under the hood
* use the new label parser for CCB
* Implement the new ccb reduction that converts a ccb multiline example into a sequence of cb multi-line examples. Between 2 cb call, previously chosen actions are removed from all available actions
* implement the explicit inclusion logic, that overrides the list of available actions
Some remaining work should be done, in order to have a functional CB:
* decision features should be used (currently ignored)
* decision features should be crossed with all other features (shared and actions)
* handle console 'printing' - currently broken for CCB
> [CCB] Add ccb_explore_adf reduction

- cluster/CMakeLists.txt
This addresses an issue that was brought up in #1749
> Allow spanning_tree to be a static executable

- test/unit_test/ccb_parser_test.cc
- vowpalwabbit/conditional_contextual_bandit.cc
The ccb and cb format had the cost and probability opposite ways, this PR rectifies this irregularity
> Fix label cost/probability ordering to be consistent with existing cb reduction

- vowpalwabbit/cb_explore_adf.cc
Fixes #1778 
This issue was caused by the fact that the valid cb_type was being checked after the rest of the reduction stack was initialized. It needed to be done before so the default of "ips" could be used.
> Fix resetting of cb_type when using dm with cb_explore_adf

- test/unit_test/CMakeLists.txt
- test/unit_test/object_pool_test.cc
- test/unit_test/unit_test.vcxproj
- test/unit_test/unit_test.vcxproj.filters
- vowpalwabbit/lda_core.cc
- vowpalwabbit/learner.cc
- vowpalwabbit/object_pool.h
- vowpalwabbit/options_boost_po.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/parser.h
- vowpalwabbit/queue.h
- vowpalwabbit/vw_core.vcxproj
- This replaces the fixed size example ring previously used
- Therefore there is now no limit on the number of lines in a multi line example
- Fixes #1739
- VW now uses generic queue based object pool for example objects
- Parser offers ready passed examples in a FIFO producer/consumer queue with bounded size (ring size is used)
- Performance impact of this change has not yet been tested
- Simplifies logic around handling the example objects and passing to learner through these abstractions
- `used_index` is no longer relevant
- `being_parsed_examples` and `end_parsed_examples` haven't been removed yet as they are used to set the `example_counter` and hasn't been replaced
- I used inheritance to represent the interface of the object pool as I thought it made it clear. It should not impact …
> Parser now uses object and prod/cons queue and object pool for example parsing

- vowpalwabbit/bfgs.cc
fixes #1729 
Cause of problem: weights[constant] always returns 0, so there was no subtraction happening at all with the below two lines:
`(&weights[constant])[W_GT] -= regularization * weights[constant]; ret -= 0.5 * regularization * (weights[constant]) * (weights[constant]);`
This is because we weren't accessing it the right way. 
`weights.strided_index(constant)` gives us what we want. Thus, the correct code should probably be:
`(&weights.strided_index(constant))[W_GT] -= regularization * (weights.strided_index(constant));
ret -= 0.5*regularization*(weights.strided_index(constant))*(weights.strided_index(constant));`
> Fix to bug 1729: no bias regularization for BFGS not working

- CMakeLists.txt
- libvw.pc.in
With the latest cmake build process the installed file `libvw.pc` contains all the required boost libraries in a semicolon-separated list. This causes the output of `pkg-config --libs libvw` on Ubuntu 18.04 to be:
```
-L/usr/local/lib -lvw -lallreduce -pthread /usr/lib/x86_64-linux-gnu/libboost_program_options.so\;/usr/lib/x86_64-linux-gnu/libboost_system.so\;/usr/lib/x86_64-linux-gnu/libboost_thread.so\;/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so\;/usr/lib/x86_64-linux-gnu/libboost_chrono.so\;/usr/lib/x86_64-linux-gnu/libboost_date_time.so\;/usr/lib/x86_64-linux-gnu/libboost_atomic.so\;/usr/lib/x86_64-linux-gnu/libpthread.so -lz
```
which is not useful for passing to the linker.
This change separates the library paths with spaces so that a command such as `g++ $(pkg-config …
> expand Boost_LIBRARIES for pkg-config libs

- python/pylibvw.cc
This is a fix to bug https://github.com/VowpalWabbit/vowpal_wabbit/issues/1784
The problem was that the actual scores list was indexed by action. In the python binding, in `pyvw.cc`, in the function `ex_get_action_scores`, we were appending the probabilities to a list ignoring the index that specified the action. I have added a new array that stores both the index and the score and use this new array to generate the list that is returned.
> fix bug 1784: return probabilities for actions in the correct order in python binding

- vowpalwabbit/OjaNewton.cc
> Fix NaN issue in box-muller tranform

- .scripts/restore.cmd
We removed the Python3 Windows bindings project, because the bindings now build via CMake; this broke the Azure DevOps pipeline, which validates that restore.cmd worked properly.
> Fix Azure Pipeline build-break

- .pipelines/build-windows-nuget.yml
- .scripts/package.cmd
This provides a mechanism to insert version/tag during the CI/CD pipeline (thereby inserting a version generated by the pipeline).
Longer-term this will be handed by a "version generation" step, which will read the target version from a file, and create the appropriate artifacts (config.h, build.props, etc.) to be used by the appropriate build systems to inject the version. In the short term, this unblocks work on release pipeline for Windows artifacts.
> Enable Version and Tag override for NuGet pack

- library/gd_mf_weights.cc
Use right indices to write out features for the right namespace, correcting bug found in https://github.com/VowpalWabbit/vowpal_wabbit/issues/1871
> Update gd_mf_weights.cc right namespace

- vowpalwabbit/cb_adf.cc
Message was changed by mistake on cb_type softmax PR #1839
> Fixed warning message ips -> mtr

- reinforcement_learning/README.md
Since it has been 6 months since the reinforcement_learning repo was migrated I am removing the folder in this repo
> Remove reinforcement_learning folder

- vowpalwabbit/vw.vcxproj
vw.vcxprojx has wrong references, they get exposed when
added to another Visual Studio Solution.
> Change references from SolutionDir to ProjectDir

- vowpalwabbit/bfgs.cc
Fixes issue where models trained with bfgs could not invert the hash.
I copied the code from ftrl.cc which does do this correctly.  
There is also code in ftrl that does this for multipredict that I did not copy.  I was not sure when that was used.
> fix to make invert_hash work with bfgs (issue number 1891)

- vowpalwabbit/memory_tree.cc
> more warnings

- .scripts/package.cmd
Now that the version is properly generated based on the version.txt file, replace the hard-coded version with reading it in from the file.
> Remove hard-coded version in Windows CI package gen script.

- .pipelines/build-windows-nuget.yml
- .scripts/package.cmd
This enables running the Build-Windows-NuGet pipeline in "Official Build" mode, which generates a NuGet with an un-tagged, non-prerelease version: `8.7.0` vs. `8.7.0--ac162bffab30636a4a59725cdd7c899fcc4114ea--1277`
It is a NoOp for AppVeyor / non-Windows builds.
> Enable suppressing NuGet version tag for official builds

- test/train-sets/ref/cbify_regcb.stderr
- vowpalwabbit/cb_explore_adf.cc
As did in commit 4de221581418 for Tau first, this commit fixes data.counter behavior for regcb and cover
> cover and regcb: data.counter++ only in learn examples (not predict)

- .pipelines/build-macos.yml
- .scripts/macos/build.sh
- .scripts/macos/restore.sh
- .scripts/macos/test.sh
Fixes #1762 
MacOS CI currently fails with some test errors. I am merging this and turning it on so we can work against it and get those fixed. It is not a required status check so won't cause issues there.
> Enable MacOS continous integration

- vowpalwabbit/io_buf.h
This function allowed for memory leaks if called, and was not necessary.
> Remove io_buf::init()

- CMakeSettings.json
- setup.py
Builds through Anaconda on OSX continues to have problems
- It looks like there are issues with system installed versions of boost and anaconda installed boost on OSX (possibly with any version of boost >= 1.70), likely due to the fact that boost changed its discovery method from cmake in 1.70.
- If Anaconda is NOT installed, this change fixes the build for OSX 10.14
- This change SHOULD be safe for all versions of boost. Tested in OSX (boost 1.71), Ubuntu (boost 1.67),  and Windows(boost 1.69). If this isn't safe, then there's not really a way to fix the build scripts since we can't tell which version of boost we have until we're actually in cmake
Also made a change that fixes a minor build issue on Windows. With VS2017 generators, we no longer need to set the VCTargetsPath variable when …
> Fix OSX builds when not using Anaconda.

- CMakeLists.txt
Xcode 11 changed their defaults and started turning stack check on (see New Features)
https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes#3319458
Also there is a bug that with certain combinations of flags check-stack related calls become unaligned.
There are many discussions about that, i. e.
https://forums.developer.apple.com/thread/121887
Current change is mitigating the issue with turning off stack-check by default.
#2151
> Catalina segfault mitigation

- CMakeLists.txt
- explore/CMakeLists.txt
- libvw.pc.in
- libvw_c_wrapper.pc.in
- vowpalwabbit/CMakeLists.txt
- vowpalwabbit/slim/src/CMakeLists.txt
- Fix pkgconfig files
- Install headers to vowpalwabbit subdir
- Install Slim headers
This change fixes a regression in 8.7.0. In the change to CMake install locations were accidentally modified, this change resolves that.
Fixes #2165
> Fix header install locations

- explore/future_compat.h
- python/pylibvw.cc
- test/unit_test/CMakeLists.txt
- test/unit_test/cb_explore_adf_test.cc
- test/unit_test/ccb_test.cc
- test/unit_test/dsjson_parser_test.cc
- test/unit_test/example_header_test.cc
- test/unit_test/json_parser_test.cc
- test/unit_test/tokenize_tests.cc
- test/unit_test/vwdll_test.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_args.h
- vowpalwabbit/parse_primitives.cc
- vowpalwabbit/parse_primitives.h
- vowpalwabbit/parser.h
- vowpalwabbit/vw.h
- vowpalwabbit/vwdll.cpp
- vowpalwabbit/vwdll.h
- Adds functionality for escaped strings when using the library initialize function
- Expose escaped command line through c interface
- Add `--quiet` to unit tests to fix output pollution
- Add deprecated macro
Fixes #2124
> Allow escaped command lines

- python/pylibvw.cc
- test/unit_test/ccb_parser_test.cc
- vowpalwabbit/ccb_label.cc
Fixes #2116
Fixes #2170
This fix is a bit concerning. I don't know why cached labels are not defaulted before being written into.
> Default the label for CCB when reading cached labels

- python/tests/test_sklearn_vw.py
- python/vowpalwabbit/sklearn_vw.py
- requirements.txt
The Sklearn lib was saving and loading in a custom non standard way, I migrated to using the normal  model loading code. 
Fixes #2120
> Use standard save/load functionality for sklearn Python lib

- python/examples/Learning_to_Search.ipynb
- python/examples/covington.py
- python/examples/test_search.py
- python/examples/test_search_ldf.py
- python/vowpalwabbit/pyvw.py
- vowpalwabbit/search.cc
Fixes a set of issues in search bindings and corresponding examples. 
In PR #1837, we unified how examples in Python are disposed (to enable properly cleaning up multi example lists, and ensure we are doing the right type of dispose). This resulted in removing the ability to use the `with ... as` construction in Python, but we failed to update the example scripts.
This fixes the issues seen in #1861 and #2144 (commenting out the LDF examples which do not currently work).
As well, in PR #1296, we added a safety check in Python to ensure we do not pass oracles with values of 0. Similarly to above, we did not properly update the example scripts. As well, in LDF mode, we always expected the multi-example provided to have an example header, but this does not occur in the example cases. The fix …
> Fixes for Learning2Search Subsystem

- python/pylibvw.cc
There were several Python issues and it seem that the root cause is the deleter for the objects. I incorrectly put in a fix for a memory leak some time ago (PR #2153), but the leak itself was fixed elsewhere in 8.8.0 and the deleter I used was wrong. It caused double finish behavior which broke other things.
Fixes #2193 
Fixes #2199 
Fixes #2202
> Fix delete behavior for examples created using parse function

- cs/cli/vw_clr.vcxproj
.Net NuGet packages have some troubles being referenced from inside of C++/CLI projects. The workaround is to pull the NuGet separately, then directly reference the dependency inside of the vcxproj. Unfortunately, this leads to situations where the version number gets desynced.
Going forward we will be rebuilding our C# (.Net) bindings to be .Net Standard-compatible, and multi-platform, similar to how it is done in VowpalWabbit/reinforcement_learning; this will necessitate moving away from C++/CLI and will fix this issue. The short-term mitigation is to manually fix up the version number.
> Fix version of NewtonSoft used by in vw_cli.vcxproj

- test/RunTests
Fixes cases where RunTests would fail to fuzzy compare:
- Audit output because of `@`
- CB predictions because of `,`
- Some progressive validation because of use of `...`
Fixes #2194
> Fix some cases where fuzzy compare would not work in RunTests

- CMakeLists.txt
We need to state we will use NEW behavior for this policy. This means that `target_sources` will convert relative paths to absolute paths.
> Silence cmake warning for policy CMP0076

- python/vowpalwabbit/pyvw.py
- python/vowpalwabbit/sklearn_vw.py
- vowpalwabbit/gdb_pretty_printers.py
As per the [wiki](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Maintainer-Info), the python code has been made adhering and all style and refactoring has been done.
0. [style] Make python files adhere to yapf guidelines
- As per the instructions in Maintainer-info wiki, the python files should adhere to the yapf standard
- https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Maintainer-Info
0. [style] Make gdb_pretty_printers.py adhere to pylint standards
- `gdb_pretty_printers.py` has been refactored in order to adhere to the pylint standards set in Maintainer-info wiki
> [STYLE] Make Python Files Adhere To Set Linting Standards

- python/tests/test_pyvw.py
- python/vowpalwabbit/pyvw.py
Fixes #2345
The `example` object has no attribute `get_multiclass_probabilities`, therefore, this was changed to `get_scalars` (`pMULTICLASSPROBS`)
> Fixes AttributeError in multiclass_probabilities_label

- python/docs/source/conf.py
- python/vowpalwabbit/__init__.py
- python/vowpalwabbit/version.py
Fixes #2349 
Fixes #2357 
* python
* Auto-read version from version.txt while building docs for python
* Add an attribute `__version__`
Added an attribute __version__ to provide the version of the currently used vowpalwabbit. The same will be used in `conf.py` for auto-update wihle creating docs.
Example:
```
>>> import vowpalwabbit
>>> vowpalwabbit.__version__
'8.8.0'
```
> Auto-read version in conf.py for docs from version.txt

- .github/workflows/build_docs.yml
This stops failures in forks where the secret is not present
> Limit documentation upload to only happen on main repository

- .gitignore
Added `tmp.model` to `.gitignore` created while running python tests
> Ignore tmp.model

- CMakeLists.txt
- Also remove C flags as we have no C code.
Fixes #2371
> Only override RelWithDebInfo flags for non MSVC situations

- python/tests/test_sklearn_vw.py
- python/vowpalwabbit/sklearn_vw.py
Partial fix for #1469
* Prevents overwriting  the `passes` when data is passed at object creation
> Prevent overwriting passes when data is passed in VW at object creation

- .gitignore
- vowpalwabbit/vw.h
The mainpage was blank up until now, this just adds some very basic contents to avoid confusing the user with a blank page.
> Add basic contents to the doxygen mainpage

- vowpalwabbit/array_parameters.h
In this situation the old explicit constructor can be replaced with defaults. It also makes sense to add  default move constructors as well.
This fixes a warning that was turned on in Clang 10.
> Fix warning where only copy assignment constructor was defined

- library/CMakeLists.txt
- library/ezexample_predict_threaded.cc
- vowpalwabbit/ezexample.h
- Remove Boost::thread dependency from project
- Cleanup ezexample_predict_threaded
- Fix bug in ezexample
> Remove Boost::thread dependency

- vowpalwabbit/options.h
- vowpalwabbit/options_serializer_boost_po.cc
- vowpalwabbit/options_serializer_boost_po.h
`options_serializer_boost_po::data()` previously returned a reference to the temporary local object `m_output_stream.str()`. This required a change to the interface of the `options_serializer_i` class to signal the caller that they must own this memory. This function is not being used anywhere, so the other option was simply to remove.
This fixes a warning introduced in Clang 10.
> Fix return reference to temporary local bug

- test/unit_test/distributionally_robust_test.cc
- vowpalwabbit/memory.h
- Since we target C++11 we require our own `make_unique` helper
- `scoped_calloc_or_throw` would leak memory if a constructor threw, this fixes that potential leak
- `distributionally_robust_test.cc` used `std::make_unique` which is not available in C++11, change it to use our helper
> Add VW::make_unique, fix exception safety issue

- vowpalwabbit/CMakeLists.txt
- vowpalwabbit/cb_explore.h
- vowpalwabbit/compat.h
- vowpalwabbit/learner.cc
- vowpalwabbit/learner.h
- vowpalwabbit/reductions_fwd.h
This PR migrates the LEARNER namespace to be under VW::LEARNER, but also provides an alias to avoid breaking existing functionality.
The ultimate goal being all VW functionality existing below the root namespace, and changing all namespaces to be lowercase for consistency.
Related: #1769 
Follow up branch: https://github.com/jackgerrits/vowpal_wabbit/tree/jagerrit/fix_LEARNER_usage
> Migrate LEARNER namespace to VW::LEARNER, provide compat header

- vowpalwabbit/global_data.h
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parser.cc
When a model is saved in active learning mode, it resumes active learning when loaded (i.e., it starts listening for input on a port and ignoring local sources).
This option allows the user to change this behaviour (so that the Python library can interact with the loaded model, for example).
> Added `--local` option (for loading active learning/damon models)

- setup.py
Adding debug option to avoid modifying the script every time as explained on: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Python#steps
```
Ensure VW bindings are installed as debug 2. Right now this means editing line 88 of setup.py and
setting config to 'debug' 3. Then run setup.py install -f under the repo root to install the bindings
> Add debug option to setup python script

- vowpalwabbit/cb_algs.cc
- vowpalwabbit/cb_explore.cc
- vowpalwabbit/cb_explore_adf_rnd.cc
- vowpalwabbit/csoaa.cc
- vowpalwabbit/gen_cs_example.h
- vowpalwabbit/learner.h
- vowpalwabbit/shared_feature_merger.cc
- vowpalwabbit/warm_cb.cc
In GD, when there is a feature with too much magnitude, VW [throws](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L494) out of the learn() function. This causes a failure to restore labels properly when propagating up the stack, in particular in [GEN_CS::call_cs_ldf<>](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/gen_cs_example.h#L282-L286). In library mode this results in example objects which throw AccessViolation on cleanup.
The fix is to use RAII ([scope_exit](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/scope_exit.h#L58)) to ensure the appropriate cleanup code runs.
> Fix CB state corruption when GD THROWs

- .clang-format
The previous clang-format file was very large and hard to reason about. I've updated it to base on the Google style guide (which we pretty much follow already).
- Simplify format
- Base it on Google style
- Fix: pointer and reference alignment
- `thing *a;` -> `thing* a;`
- Change: short loops and functions on single line from allowed to disallowed
Running this new file results in **very few changes**. The few changes that do occur are either:
- An existing formatting inconsistency
- Fixing the pointer alignment
- Changing single line loops or functions to be over several lines
- This is a personal preference thing but as it is inconsistent in the code base I figured I would set a guide in the format file. Preferably all blocks would use braces (yet again, opinion)
> Simplify clang-format and small fixes and changes

- .clang-tidy
This allows for easy running of clang-tidy without needing to specify checks each time. Additionally allows for easy integration with clangd.
> Create .clang-tidy file 

- test/unit_test/CMakeLists.txt
- test/unit_test/error_test.cc
- test/unit_test/unit_test.vcxproj
- test/unit_test/unit_test.vcxproj.filters
- vowpalwabbit/action_score.cc
- vowpalwabbit/active.cc
- vowpalwabbit/allreduce_sockets.cc
- vowpalwabbit/bs.cc
- vowpalwabbit/cb_adf.cc
- vowpalwabbit/confidence.cc
- vowpalwabbit/csoaa.cc
- vowpalwabbit/decision_scores.cc
- vowpalwabbit/global_data.cc
- vowpalwabbit/mwt.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/search.cc
- vowpalwabbit/topk.cc
- vowpalwabbit/vw_exception.h
`strerror` is deprecated and not threadsafe. This PR replaces usage with the platform specific safe versions:
- `strerror_s` on Windows
- `strerror_l` on Linux
> Migrate away from deprecated strerror function

- CMakeLists.txt
- explore/future_compat.h
- vowpalwabbit/learner.h
- Use warning framework to silence the known usage of these untyped function pointers in learner
- This uncovers some other questionable usage elsewhere
> Handle cast-function-type warning explicitly in code

- explore/explore_internal.h
- vowpalwabbit/OjaNewton.cc
- vowpalwabbit/cb_explore_adf_bag.cc
- vowpalwabbit/cb_explore_adf_cover.cc
- vowpalwabbit/csoaa.cc
- vowpalwabbit/ect.cc
- vowpalwabbit/gd.cc
- vowpalwabbit/interactions.cc
- vowpalwabbit/lda_core.cc
- vowpalwabbit/mf.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_example.cc
- vowpalwabbit/parse_slates_example_json.h
- vowpalwabbit/parser.cc
- vowpalwabbit/rand48.cc
- vowpalwabbit/search.cc
This PR resolves MSVC warnings related to local variables hiding other local or global variables with the same variable name.
Also resolves 3 small warnings related to parentheses, using a deprecated method, and using the wrong `int` type as index.
The CI should not display any more VW related warnings. However compiling with VS2019 I get more warnings locally so will work towards resolving those too.
> resolve MSVC C4456 and C4459

- test/unit_test/CMakeLists.txt
- test/unit_test/parser_test.cc
- vowpalwabbit/parse_args.cc
EDIT: Originally I thought there was a bug - but I was interpreting the code incorrectly. The purpose of this function is to be able to add a hex encoded single character. So I ended up with a little cleanup and some tests.
> Add test for spoof_hex_encoded_namespaces

- test/unit_test/vwdll_test.cc
This reduces the logging output (by ALOT) when using more verbose Boost test logging.
> Use collection comparison instead of iterating over the collection and comparing

- python/pylibvw.cc
- python/tests/test_pyvw.py
- python/vowpalwabbit/pyvw.py
Fixes a few things.
1. deleting the vw object in python did not result in its destruction
1. `finish_example` cannot be called on an example that has not been used. Doing so on Windows will cause it to crash (this behavior appears to have existed for a while, an incorrect test simply exposed it)
1. Creating a DataFrame with int values will generate a DataFrame containing `int64`s. However, the default conversion of `int`->`pandas_dtype` on Windows is `int`->`int32`. This causes type mismatch errors when performing our type checks in DFtoVW.
I'm not completely sure of the ramifications of the vw deletion change though; on the surface it makes sense and all of the tests pass. However there may be some subtle interactions with how we implement the python wrappers or how they're being used …
> Fix python tests on Windows

- vowpalwabbit/CMakeLists.txt
- vowpalwabbit/api_status.cc
- vowpalwabbit/api_status.h
- vowpalwabbit/error_constants.h
- vowpalwabbit/error_data.h
- vowpalwabbit/vw_core.vcxproj
Once #2493 is merged, I am going to propose the following changes:
- Rename from `api_status` to `error_message`
- Removal of `error_code` from `api_status` object
- Change from int to enum based error codes
- Usage of `[[nodiscard]]` for error code returns
- Saving of the failure stack when propagating errors
> Migrate error codes implementation from #2493 and move into experimental namespace

- CMakeLists.txt
- test/CMakeLists.txt
- Adds C API into CI
- `Boost::unit_test_framework` is only required if `BUILD_TESTS` is enabled
> [CAPI] Ensure c bindings test runs as part of test_with_output

- .clang-format
This option means that nested preprocessor directives will be nested, which is something we tend to do already (although it is uncommon). By default they are flattened.
[Description from docs](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
> [fmt] Add preprocessor indent format option

- .clang-format
This reverts commit dc91fe27f274e25dcdc93453a33d081dc6293ebd.
The added option requires clang 9 which is too recent to reasonably depend on.
> Revert "Add preprocessor indent format option (#2554)"

- vowpalwabbit/CMakeLists.txt
The core reason is that we don't want to create or install a libvw_io.a file, this CMake target is only intended to make internal lib organization easier.
> [Build] Make vw_io an object library 

- bindings/c/include/vw/experimental/types.h
- Previously it was using the header exposed from the `VowpalWabbit::vw` target, when using this externally, that will not be available.
> Fix include path to use header out of binary dir

- .github/workflows/build_python_wheels.yml
We can turn this back when 3.9 is released fully.
> Don't test 3.9 wheel for now 

- python/CMakeLists.txt
- test/unit_test/CMakeLists.txt
This is not directly used anywhere so transitive link targets should bring it in if needed.
> Remove Boost::system dependency from CMake files

- CMakeLists.txt
The last bit of code referencing this was removed [here](https://github.com/VowpalWabbit/vowpal_wabbit/pull/2379), so we can remove it as a dependency now.
> Remove Boost::thread dependency from CMake files

- vowpalwabbit/CMakeLists.txt
Reverts VowpalWabbit/vowpal_wabbit#2564
This breaks older versions of cmake.
Fixes #2587
> Revert "[Build] Make vw_io an object library "

- test/unit_test/dsjson_parser_test.cc
- vowpalwabbit/parse_example_json.h
Change the DSJSON parser to support both "p" and "_p":
- When the "_p" key is inside "c", its parsing is ignored.
- When duplicate "p" or "_p" are present, the latest one is used.
> Support using "_p" in DSJSON parser.

- python/tests/test_pyvw.py
- python/vowpalwabbit/pyvw.py
This PR fix issue #2600.
- The feature that allow the user to supply constant value instead of column names as argument in classes DFtoVW (and friends) is removed.
- In the `Feature` class, the name provided can only be a constant string now and not a column name.  Indeed, since now the user cannot choose whether the argument `name` is a constant or a column name, it's by default a constant.
> Remove the possibility in DFtoVW to provide constant values

- python/tests/test_DFtoVW.py
- python/vowpalwabbit/DFtoVW.py
This PR fix issue #2505 
4 modifications:
- Add default feature name based on the related colname. The method `_Col.get_colname` has been created, it also slugify the colname (removing " " and ":" if present)
- Default separator is based on the pandas column type. 
- The possibility to enforce a type has also been add in `Feature` using `as_type` argument (as suggest by @olgavrou). Note that if the user select `as_type="numerical"` for a column of strings that do not represent number _underneath_ (e.g "a", "b" instead of "1", "1.5", etc.) no warning is raised. If necessary I can add warning.
- changes some tests to match the default colname behavior. Add new tests (for instance related to `as_type`).
@lalo feel free to add any change if you want to contribute on this PR :)
> Default feature name based on pandas colname, default VW separator based on type

- vowpalwabbit/allreduce_sockets.cc
- vowpalwabbit/v_array.h
C4005: v_array.h redefines the `NOMINMAX` macro, it needs to be behind #ifndef
C4242: `AllReduceSockets::sock_connect` has `const int port` as input, but passes it into several functions that are of the `u_short` type. The explicit cast bypasses the warning.
> Fix msbuild warnings C4005, C4242

- test/RunTests
- test/train-sets/explore_eval.dat
- test/train-sets/ref/explore_eval_uniform_distributed_policy.stderr
- vowpalwabbit/cb_adf.cc
- vowpalwabbit/cb_adf.h
- vowpalwabbit/explore_eval.cc
The input format within the reductions seem to be inconsistent. Some of the reductions assuming "shared" is required, but parser doesn't require example to have "shared". 
So the action index between `get_observed_cost` and the `example sequence` are different if shared feature exists. For `explore_eval` we skip the shared features to keep the action index consistent.
> bug fix: action index is inconsistent in explore_eval

- .github/workflows/build_python_wheels_macos.yml
Github deprecated a certain way of changing paths: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This was used in the action ` conda-incubator/setup-miniconda` and has been fixed in v2.0.0 https://github.com/conda-incubator/setup-miniconda/releases/tag/v2.0.0
Upgrading our dependency on them to resolve the CI failures.
> Fix deprecation in MacOS Python CI

- test/RunTests
To ensure runs are identical cache tests should use kill cache
> Use kill cache in test using cache

- cluster/CMakeLists.txt
- cluster/cluster.vcxproj
- cluster/spanning_tree_main.cc
In order to parallelize tests, they need to run on different ports. This allows us to supply the spanning tree tool with a custom port.
> Allow port to be selected in spanning tree tool

- python/pylibvw.cc
- python/tests/test_cats.py
- python/vowpalwabbit/pyvw.py
The pdf prediction type (`VW::continuous_actions::probability_density_function`) is the one used by `cats_pdf`.
It is also the prediction type used by #2410 and thus having Python bindings would be helpful.
> Add python bindings for pdf prediction type

- test/RunTests
Probably just a nit but the first time I wrote these tests it seemed necessary to reference the previous test whose output file is being used in the current test. Not sure how they passed without that being correct. Nevertheless fixing it.
> Fix cbzo test dependency mention

- vowpalwabbit/cb_explore_adf_synthcover.cc
- vowpalwabbit/cbify.cc
- vowpalwabbit/continuous_actions_reduction_features.h
- vowpalwabbit/debug_print.h
- vowpalwabbit/io_buf.h
- vowpalwabbit/search.cc
- vowpalwabbit/v_array.h
Make v_array.h more lightweight of a file to bring in.
Remove dead code:
- pop
- vstring
- v_move, v_extract
Move printing functions to debug_print.h
> v_array cleanup

- cs/cli/vw_base.cpp
- java/src/main/c++/jni_spark_vw.cc
- library/libsearch.h
- python/pylibvw.cc
- vowpalwabbit/baseline.cc
- vowpalwabbit/cbify.cc
- vowpalwabbit/example.cc
- vowpalwabbit/expreplay.h
- vowpalwabbit/memory_tree.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/search.cc
- vowpalwabbit/search_dep_parser.cc
- vowpalwabbit/search_entityrelationtask.cc
- vowpalwabbit/search_sequencetask.cc
- vowpalwabbit/vw.h
- vowpalwabbit/warm_cb.cc
The old `dealloc_example` call would destruct but not free, was confusing to use and did not match with the alloc_examples call that was right next to it. This fixes that up
> Fix confusing API - dealloc_example

- test/run_tests.py
This prevents flaky parallel failures when multiple bash based tests operate on the same files
> Inject artificial dependencies for bash script based tests

- test/run_tests.py
- test/runtests_parser.py
Useful when resolving RunTests merge conflicts, and avoiding being misled by other errors down the line.
> [test] check for missing test ids

- vowpalwabbit/cb_explore_pdf.cc
- vowpalwabbit/cb_label_parser.h
- vowpalwabbit/ccb_label.cc
- vowpalwabbit/cost_sensitive.cc
- vowpalwabbit/example.cc
- vowpalwabbit/memory_tree.cc
- vowpalwabbit/mf.cc
- vowpalwabbit/multilabel.cc
- vowpalwabbit/slates_label.cc
- vowpalwabbit/v_array.h
- vowpalwabbit/warm_cb.cc
std::copy will use memcpy under the hood
> Deprecate explicit copy functions and use std::copy as implementation

- .pipelines/build-windows-nuget.yml
When adding caching of NuGet packages, we added caching of the outputs of the build. This causes issues around persisting old packages when the version number changes.
> Remove caching of Windows CI build targets

- .github/workflows/check_pr_title.yml
> When using "Squash and merge" on a PR with only one commit, GitHub will suggest using that commit message instead of the PR title for the merge commit, and it's easy to commit this by mistake. Enable this option to also validate the commit message for one commit PRs.
> ci: Update check_pr_title.yml

- vowpalwabbit/cb.cc
- vowpalwabbit/cb_algs.cc
- vowpalwabbit/cb_continuous_label.cc
- vowpalwabbit/cb_label_parser.h
- vowpalwabbit/ccb_label.cc
- vowpalwabbit/ccb_label.h
- vowpalwabbit/cost_sensitive.cc
- vowpalwabbit/cost_sensitive.h
- vowpalwabbit/label_parser.h
- vowpalwabbit/multiclass.cc
- vowpalwabbit/multilabel.cc
- vowpalwabbit/no_label.cc
- vowpalwabbit/search.cc
- vowpalwabbit/simple_label.cc
- vowpalwabbit/simple_label_parser.cc
- vowpalwabbit/slates.cc
- vowpalwabbit/slates_label.cc
- vowpalwabbit/slates_label.h
- vowpalwabbit/warm_cb.cc
> refactor: Remove delete_label

- vowpalwabbit/cb_adf.cc
CB_TYPE_DR || CB_TYPE_DM resolves to 0 || 1 which is equal to 1.  This bug results in an extra call to predict() for CB_TYPE_DR.
> fix: cb_adf learn_returns_prediction() incorrect or condition

- test/unit_test/dsjson_parser_test.cc
- vowpalwabbit/parse_example_json.h
Fix #2962 
When pdrop (or other expected float) is 0 instead of 0.0 in json, an error is thrown.
This makes sure that floats can be produced from unsigned ints as well.
Added UTs.
> fix: Adding Uint handling to FloatToFloatState

- vowpalwabbit/OjaNewton.cc
- vowpalwabbit/active.cc
- vowpalwabbit/active_cover.cc
- vowpalwabbit/best_constant.cc
- vowpalwabbit/binary.cc
- vowpalwabbit/cats.cc
- vowpalwabbit/cb_explore_adf_regcb.cc
- vowpalwabbit/cb_explore_adf_squarecb.cc
- vowpalwabbit/cs_active.cc
- vowpalwabbit/csoaa.cc
- vowpalwabbit/ftrl.cc
- vowpalwabbit/gd.cc
- vowpalwabbit/kernel_svm.cc
- vowpalwabbit/memory_tree.cc
- vowpalwabbit/mwt.cc
- vowpalwabbit/nn.cc
- vowpalwabbit/oaa.cc
- vowpalwabbit/plt.cc
- vowpalwabbit/pmf_to_pdf.cc
- vowpalwabbit/stagewise_poly.cc
Automated fixed applied with `clang-tidy`
Check: `performance-type-promotion-in-math-fn`
> fix: Avoid float to double promotion by using C++ version of math functions

- vowpalwabbit/array_parameters_dense.h
- vowpalwabbit/audit_regressor.cc
- vowpalwabbit/gd.cc
- vowpalwabbit/learner.h
- vowpalwabbit/parse_regressor.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/search_dep_parser.cc
- vowpalwabbit/spanning_tree.cc
- vowpalwabbit/vw_exception.h
Automated fixed applied with `clang-tidy`
Check: `modernize-use-nullptr`
> refactor: use nullptr instead of NULL

- python/tests/test_DFtoVW.py
- python/vowpalwabbit/DFtoVW.py
Importance weight is part of the VW specification for Simple label (see https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Input-format#simple) but was not implemented/forgotten in `DFtoVW.SimpleLabel`. 
For instance, the previous `SimpleLabel` class could not handle this user's needs: https://stackoverflow.com/questions/65385962/how-to-convert-csv-columns-into-vowpal-wabbit-txt-input-file/65387264#65387264
I named the attribute `weight` but I can change it to `importance` if necessary.
The usage is the following:
```python
import pandas as pd
from vowpalwabbit.DFtoVW import DFtoVW, Feature, SimpleLabel
df = pd.DataFrame({
"y": [1, 2, -1],
"w": [2.5, 1.2, 3.75],
"x": ["a", "b", "c"]
})
sl = SimpleLabel(label="y", weight="w")
conv = DFtoVW(df=df, label=sl, features=Feature("x")) …
```
> feat: [py] DFtoVW -> Add weight attribute to SimpleLabel

- vowpalwabbit/example.cc
- vowpalwabbit/feature_group.h
- vowpalwabbit/interact.cc
- vowpalwabbit/label_dictionary.cc
- vowpalwabbit/mf.cc
- vowpalwabbit/namespaced_features.h
- vowpalwabbit/nn.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_example_json.h
- vowpalwabbit/parse_slates_example_json.h
- vowpalwabbit/search.cc
This was deleted in the past to prevent accidental copies, however to aid composition of components I believe the copy constructor being available is convenient. This is directly helpful to the current PR I am working on for `namespaced_features` migration. Additionally, accidental copies should show up in the benchmarks CI
> refactor: Use default copy constructor for `features`

- vowpalwabbit/cb_sample.cc
Refactor cb_sample.cc to use builder to set features of learner
> refactor: Refactor cb_sample.cc to use builder to set features of learner

- test/RunTests
- test/train-sets/ref/baseline_test.stderr
- vowpalwabbit/baseline.cc
- vowpalwabbit/constant.h
This unblocks namespaced features
> fix: Baseline should signal its enablement through an index and not a feature

- vowpalwabbit/io/logger.cc
- vowpalwabbit/io/logger.h
VowpalWabbit should not modify global logging settings (since it's a library), but it [does](https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L1771) every time we initialize a new model.
This MR fixes that.
I also noticed that `_stderr_logger` is not thread-safe so I changed it to the `_mt` variant.
> fix: do not change spdlog global settings

- python/tests/test_DFtoVW.py
- python/vowpalwabbit/DFtoVW.py
DFtoVW converter doesn't handle well None/np.nan value when present in the pandas DataFrame.
For example if the value is missing for a given feature it will output `"feature:"` (or `"feature="` if categorical ) on the parsed line.
This PR fixes this issue (+ add a test). The value will just be `" "` if the feature value is missing.
> fix: [DFtoVW] Fix issue with nan/None in feature

- CMakeLists.txt
This bug caused RelWithDebInfo to not work on Windows
> build: MSVC check must be done after project call

- vowpalwabbit/log_multi.cc
- vowpalwabbit/memory_tree.cc
- vowpalwabbit/search.cc
- vowpalwabbit/v_array.h
deprecate: `v_array::find_sorted`, `v_array::unique_add_sorted`, `v_array::contain_sorted`, `v_array_contains`
> refactor: deprecate some v_array functions

- test/RunTests
- test/runtests.AUTOGEN.json
- test/runtests_parser.py
- test/train-sets/ref/cb_adf_mtr_cache.stderr
- test/train-sets/ref/cb_adf_mtr_cache_2.stderr
- vowpalwabbit/cb_continuous_label.cc
- vowpalwabbit/cb_label_parser.h
The label caching code was not following the io_buf contract expectations: It was not updating the buffer pointer after writing using `.set()`, and it was not properly requesting space for the weight field. This prevented the weight field from being persisted.
The fix is to update the caching code to properly `.set()` when writing using `buf_write()`, and to use `write_value()`/`read_value()` when storing the weight.
Fixes #3139
> fix: Fix CB label caching

- .github/workflows/build_python_wheels_windows.yml
CMake 3.21 (which the Github runner recently upgraded to) introduced an [issue](https://github.com/microsoft/vcpkg/issues/18718) which caused vcpkg to crash. Vcpkg has fixed this in master but we must use old versions of vcpkg to get specific port versions. [This](https://gitlab.kitware.com/cmake/cmake/-/issues/22444) tracks the status on CMake.
This PR mitigates the issue by downgrading the version of CMake used to 3.20.x for the broken workflows.
> ci: Fix Python Windows CI issue

- test/unit_test/CMakeLists.txt
- test/unit_test/custom_reduction_test.cc
- test/unit_test/minimal_custom_reduction.cc
- test/unit_test/unit_test.vcxproj
- test/unit_test/unit_test.vcxproj.filters
- vowpalwabbit/cached_learner.h
- vowpalwabbit/parse_args.cc
- vowpalwabbit/reduction_stack.cc
- vowpalwabbit/reduction_stack.h
- vowpalwabbit/reductions_fwd.h
- vowpalwabbit/vw.h
This PR adds the following experimental init fn to vw.h:
```
// Experimental (VW::setup_base_i):
vw* initialize_with_builder(std::string s, io_buf* model = nullptr, bool skipModelLoad = false,
trace_message_t trace_listener = nullptr, void* trace_context = nullptr,
std::unique_ptr<VW::setup_base_i> = nullptr);
```
This allows any user of VW to alter the reduction stack or augment it as they find fit. See unit tests for examples of flexibility. They are able to inherit from our concrete impls of setup_base_i or provide their own.
This could also be leveraged by https://github.com/VowpalWabbit/vowpal_wabbit/pull/2971
> feat: ability to customize learner builder in vw.h

- python/docs/source/tutorials/python_Contextual_bandits_and_Vowpal_Wabbit.ipynb
Updates link to the Python examples folder. 
I noticed that on https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/tutorials/python_Contextual_bandits_and_Vowpal_Wabbit.html the link at the very bottom 404'd and didn't lead properly to the example folder. This should fix this by changing the link within the Jupyter notebook.
> fix: [docs] Update link to Python notebook examples

- vowpalwabbit/cats_tree.cc
- vowpalwabbit/cats_tree.h
- vowpalwabbit/cb.h
- vowpalwabbit/cb_explore_adf_regcb.cc
- vowpalwabbit/cb_explore_adf_squarecb.cc
- vowpalwabbit/cbify.cc
- vowpalwabbit/conditional_contextual_bandit.cc
- vowpalwabbit/cost_sensitive.h
- vowpalwabbit/csoaa.cc
- vowpalwabbit/prob_dist_cont.h
- vowpalwabbit/search.cc
- vowpalwabbit/v_array_pool.h
- vowpalwabbit/warm_cb.cc
- `v_array` causes warnings when used with non-trivial types due to use of `memset`, switch these types to `std::vector`
> fix: fix gcc warnings

- vowpalwabbit/distributionally_robust.cc
reference the python impl for more info: https://github.com/VowpalWabbit/vowpal_wabbit/blob/6dffa86e04294ba9791ae1dba81de3aa9b5dc60d/test/unit_test/DistributionallyRobustUnitTestData.py#L90
> fix: missing min compare in ChiSquared impl

- test/unit_test/explore_test.cc
- test/unit_test/simulator.cc
- test/unit_test/simulator.h
- test/unit_test/tutorial_test.cc
1) remove print from explore_test.cc
2) shift things around from tutorial_test.cc to simulator.h
3) add callback hook to simulator
> test: unit tests improvements

- .gitignore
The '.*' pattern is too aggressive, it means changes to .scripts or .github are ignored
> chore: remove '.*' from .gitignore

- .gitignore
`CMakeUserPresets.json` is a file to be used locally for CMake presets and should not be checked into source control according to: https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html
> chore: add CMakeUserPresets.json to .gitignore

- vowpalwabbit/cb.cc
- vowpalwabbit/options.h
- vowpalwabbit/version.cc
- vowpalwabbit/version.h
Found with checks:
- performance-unnecessary-copy-initialization
- performance-for-range-copy
- performance-move-const-arg
> fix: perf issues found by clang-tidy

- test/train-sets/ref/corrupt_weights_gd_mf.stderr
- vowpalwabbit/OjaNewton.cc
- vowpalwabbit/bfgs.cc
- vowpalwabbit/boosting.cc
- vowpalwabbit/cb_adf.cc
- vowpalwabbit/cb_explore.cc
- vowpalwabbit/cb_explore_adf_cover.cc
- vowpalwabbit/cb_explore_adf_first.cc
- vowpalwabbit/cb_explore_adf_regcb.cc
- vowpalwabbit/cb_explore_adf_squarecb.cc
- vowpalwabbit/cb_explore_adf_synthcover.cc
- vowpalwabbit/conditional_contextual_bandit.cc
- vowpalwabbit/distributionally_robust.h
- vowpalwabbit/ftrl.cc
- vowpalwabbit/gd.cc
- vowpalwabbit/gd_mf.cc
- vowpalwabbit/io_buf.h
- vowpalwabbit/kernel_svm.cc
- vowpalwabbit/lda_core.cc
- vowpalwabbit/log_multi.cc
- vowpalwabbit/marginal.cc
- vowpalwabbit/mwt.cc
- vowpalwabbit/parse_regressor.cc
- vowpalwabbit/plt.cc
- vowpalwabbit/stagewise_poly.cc
- vowpalwabbit/svrg.cc
This functionality was used in a single placed amongst over a hundred callsites. Move the functionality to the single caller who cares
> refactor: remove redunant read message from reading interface

- python/vowpalwabbit/sklearn_vw.py
On line 833 there is the following: `return self.classes_[indices]`, which will error out unless `self.classes_` is a numpy array.
> fix: `self.classes_[indices]` in sklearn VW

- .github/workflows/run_benchmarks.yml
This should reduce number of runs the workflow will need to run
[Docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency)
> ci: Cancel previous benchmarks in a given PR when new commits pushed

- test/benchmarks/input_format_benchmarks.cc
- Uses a single file/reader and resets it between runs 
- Changes c-style array to std::array
- Removes unused test - let me know if this was used somewhere I didn't see
> ci: [fix] reuse a single file instead of adding files on each iteration for input format benchmarks

- vowpalwabbit/search.cc
```
warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct Search::action_repr’; use assignment or value-initialization instead [-Wclass-memaccess]
```
> fix: warning in search

- .pipelines/build-windows-nuget.yml
There seems to be an issue with Cache jobs on Azure devops. It is affecting one of our Windows builds. See here: https://github.com/microsoft/azure-pipelines-tasks/issues/15518
> fix: workaround Windows ADO cache job failures

- .pipelines/build-macos.yml
CI stopped working due to MacOs image 10.14 not been found since Friday, thanks @bassmang for noticing
https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/
> fix: update macOS image to 10.15

- test/train-sets/ref/help.stdout
- test/train-sets/ref/help_cbadf.stdout
- vowpalwabbit/parse_args.cc
IMPORTANT: This is not `--quadratic`, this was a weird argument that did nothing and conflicts with this argument. Removing this should help resolve any confusion with this arg.
> fix!: remove deprecated and confusing --q: argument (not -q ::)

- .github/workflows/build_python_wheels_aarch64.yml
This is consistent with other Python builds. This one just omits the PR part.
> ci: run arm python build for each commit

- python/vowpalwabbit/dftovw.py
- Add types for all functions
- Convert docstrings to Google format as it plays nicer with automatic docstring type insertion (coming in separate PR)
- This means the types will be in the docs automatically from the type hints
- `AttributeDescriptor` was is complex. I opted to represent it with `Any` for now as it is mostly internal and not user facing
- `Hashable` is used a fair bit for column names. Is this right?
CC: @etiennekintzler
> feat: add types to vowpalwabbit.dftovw

- test/train-sets/ref/cb_bad_one_of_int.stdout
- test/train-sets/ref/cb_bad_one_of_string.stdout
- utl/dump_options/main.cc
- vowpalwabbit/CMakeLists.txt
- vowpalwabbit/options.cc
- vowpalwabbit/options.h
- vowpalwabbit/options_boost_po.cc
- vowpalwabbit/options_boost_po.h
- vowpalwabbit/vw_core.vcxproj
- reduce number of add and parse implementations required by impls
- Check necessary in core impl
- Check one_of for non necessary groups
- Don't use `m_type_hash` in `get_typed_option` as the same behavior is possible
- add contains_necessary_options
> refactor: options updates

- python/tests/test_cb.py
- python/vowpalwabbit/pyvw.py
If a batch of output came in one go the log received did not properly split apart each line before.
> fix: split apart newlines in log lines forwarded to python

- .github/workflows/build_windows_cmake.yml
The CI does not work for Windows-2022 because of vcpkg.
Proper fix tracked here: https://github.com/VowpalWabbit/vowpal_wabbit/issues/3750
> ci: lock ci to windows-2019

- .github/workflows/python_wheels.yml
Merged too quickly without realizing the workflow file was invalid
> ci: fix wrong name in python CI

- utl/active_interactor.py
- utl/csv2vw
- utl/vw-csv2bin
- utl/vw-hyperopt.py
- utl/vw-lda
Python 2 was deprecated on January 1, 2020. Many up-to-date Linux distributions now use Python 3 as the default. It's time for the tools under `utl` to get upgraded to Python 3.
* Add a shebang for `active_interactor.py`
* Refactor `csv2vw`, `vw-csv2bin`, `vw-lda` for python3
* Explicitly specify `vw-hyperopt.py` to use python3 (So that we can also directly run it even on old Linux distributions who still use Python 2 as the default)
Signed-off-by: Hollow Man <hollowman@opensuse.org>
> refactor: upgrade to python3 for tools under utl

- .github/workflows/build_windows_cmake.yml
Resolves #3750: https://github.com/HollowMan6/vowpal_wabbit/runs/5615976754?check_suite_focus=true
* Upgrade vcpkg to 2022.03.10
* Remove the cmake -G option for adapting to the Visual Studio version.
As Visual Studio 16 2019 is not available in windows-2022 but Visual Studio 17 2022.
Cmake will be clever enough to find out the correct version as there's only [Visual Studio Enterprise 2022 in windows-2022](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022) and  [Visual Studio Enterprise 2019 in windows-2019 and windows-latest(currently)](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019).
Test with both windows 2019 and 2022 can be found here: …
> ci: adapt Windows CMake workflow to windows 2022

- cs/unittest/TestCbAdf.cs
Test failure tracked by #3782. Potentially irrelevant once .net core migration is complete.
> test: disable flaky test

- cluster/cluster.vcxproj
- cs/cli/vw_clr.vcxproj
- vowpalwabbit/libvw.vcxproj
- vowpalwabbit/vw.vcxproj
- vowpalwabbit/vw_core.vcxproj
With the next release being the last one containing the project files we should disable warning as error in an effort to mitigate difficulties in using them.
> build: turn off warnings as error for windows project files

- demo/random-noise/distrib.r
- demo/random-noise/vw-demo
- demo/random-noise/x-vs-y.r
vw-demo: fixes & improvements
- inline-viewer wrapper for multi-arg kitty icat
- Pause after inline image display
- case -> if
- which -> command
- explicit 'function' definitions
- Make vars local
- /bin/rm to avoid aliases
- clean_slate: explicit list of files to remove
- Add inline image display support via kitty
- shellcheck: switch `` to $(), quote args & more
- Add (*) unsupported option error check to getopts
- Add -d where missing in calls to vw
- Switch 'ImgViewCandidates' to an array
x-vs-y.r: remove commented dead-code; add --vanilla to shebang
distrib.r: remove commented dead code; add --vanilla to shebang
> feat: demo/random-noise: add inline image support + shellcheck fixes

- vowpalwabbit/core/src/parse_args.cc
the vw canary repo is using an old compiler which does not support implicit tuple creation.
> style: removed explicit tuple creation

- demo/random-noise/distrib.r
- demo/random-noise/vw-demo
- demo/random-noise/x-vs-y.r
- distrib.r, x-vs-y.r: center chart titles
- vw-demo: make one pre-command description messages more readable
- vw-demo: increase random-poly calls precision from 6 to 9 digits
- vw-demo: case's syntax consistency
- vw-demo: use 'kitty icat' only iff in pre-launched kitty window
> fix: demo/random-noise: minor fixes:

- test/train-sets/ref/help.stdout
- test/unit_test/cb_large_actions_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action_space.h
and unit tests for both epsilon greedy (no shrink factor applied) and square cb (where shrink factor should be applied)
unit tests are essentially the same but just looping over vw with square cb applied, where diag_M (diagonal matrix containing the shrink factors) is taken into account in the calculations or with epsilon greedy the diagonal scaling matrix is just the identity matrix
> feat: Apply shrink factor

- .github/codeql/codeql-config.yml
- .github/workflows/build_docs.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_vw_large_action_space.yml
- .github/workflows/build_vw_slim.yml
- .github/workflows/build_windows_cmake.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
- .github/workflows/python_wheels.yml
- .github/workflows/run_benchmarks_manual.yml
- .github/workflows/upload_coverage.yml
- .github/workflows/valgrind.yml
- CMakeLists.txt
This is intended to fix the git `fatal: unsafe repository` error in CI
Build process shouldn't download more code. Instead, submodules should be recursively updated in the initial git checkout.
> fix: Remove git submodule update in cmake

- cluster/readme.md
- ext_libs/string-view-lite/nonstd/string_view.h
There are small typos in:
- cluster/readme.md
- ext_libs/string-view-lite/nonstd/string_view.h
Fixes:
- Should read `retrieved` rather than `retreived`.
- Should read `availability` rather than `availablity`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- test/unit_test/cb_large_actions_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
to be merged after release is complete
and cleaned up tests, since we are using feature values and not feature weights we don't need to learn before predicting in the tests (we don't care if model is empty or not)
> fix: [las] A made with feature values not feature weights

- python/pylibvw.cc
- python/tests/test_pyvw.py
The c-api string encoding fails on linux operating systems when using the new dict features in vw examples. This pull request both fixes the bug and improves the unit test for the dict feature functionality so that it catches this bug.
> fix: dict processing in pyvw on linux operating systems

- vowpalwabbit/core/include/vw/core/global_data.h
- vowpalwabbit/core/src/global_data.cc
- vowpalwabbit/core/src/reductions/cb/cb_adf.cc
- vowpalwabbit/core/src/reductions/cb/cb_algs.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_cover.cc
- vowpalwabbit/core/src/reductions/scorer.cc
IGL will need to instantiate two scorer instances, we don't want to have a single one stored in workspace and be overwritten the next time you call into scorer setup func.
> refactor: [all] remove scorer from workspace

- .github/workflows/build_macos.yml
- .github/workflows/python_wheels.yml
- .github/workflows/vendor_build.yml
https://github.com/actions/virtual-environments/issues/5583
using macos-11
macos-10.15 is deprecated
macos-12 is still in beta
> ci: update macos github action to macos-11

- python/pylibvw.cc
- python/tests/test_pyvw.py
The feature index data type used by the Python layer was uint32_t while VW feature group actually used uint64_t. This pull request updates the Python layer to use VW's feature_index datatype. A unit test was added for this correction. This pull request also speeds up the Python feature_dict by 20% for integer feature values.
> fix: Correct Feature Index Data Type

- .github/workflows/build_windows_cmake.yml
- .github/workflows/vcpkg_build.yml
- .github/workflows/vendor_build.yml
- .gitmodules
- .scripts/build.cmd
- .scripts/restore.cmd
- CMakeLists.txt
- CMakePresets.json
- cmake/VowpalWabbitUtils.cmake
- test/unit_test/CMakeLists.txt
- vcpkg.json
This change makes it possible to build VowpalWabbit from a fresh clone with:
```
cmake --preset=vcpkg-debug
cmake --build --preset=vcpkg-debug
```
This also enables a user to open a fresh clone of VowpalWabbit in Visual Studio and build using CMake.
> build: Support vcpkg manifest and cmakepreset for easy building

- vowpalwabbit/core/src/accumulate.cc
Based on all known usages this set operation is redundant. Additionally, the before/after model files produced are identical.
> refactor: remove redundant set in allreduce operation

- java/src/main/c++/jni_spark_vw.cc
- java/src/main/java/org/vowpalwabbit/spark/VowpalWabbitNative.java
- java/src/test/java/org/vowpalwabbit/spark/VowpalWabbitNativeIT.java
- python/pylibvw.cc
- python/tests/test_pyvw.py
- python/vowpalwabbit/pyvw.py
- vowpalwabbit/core/include/vw/core/learner.h
- vowpalwabbit/core/include/vw/core/merge.h
- vowpalwabbit/core/src/merge.cc
- vowpalwabbit/core/src/reductions/freegrad.cc
- vowpalwabbit/core/src/reductions/gd.cc
- vowpalwabbit/core/tests/merge_test.cc
- vowpalwabbit/model_merger/src/main.cc
Uses a base image to ensure counters are not recounted from multiple model files.
Next: https://github.com/jackgerrits/vowpal_wabbit/tree/remove_voidptr_from_merger
Then: https://github.com/jackgerrits/vowpal_wabbit/tree/implement_cb_adf_merge
> feat: model merging can take a base image to merge changes over

- python/vowpalwabbit/pyvw.py
Pytype was [updated](https://pypi.org/project/pytype/#history) and started giving a false positive error. This is causing the python lint CI job to fail.
> ci: Fix pytype error

- test/unit_test/CMakeLists.txt
- test/unit_test/cb_las_one_pass_svd_test.cc
- test/unit_test/cb_las_spanner_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action_space.h
and use it to make some tests more precise
> test: [LAS] calculate num of non-degenerate singular values

- .github/workflows/vendor_build.yml
- .pipelines/build-linux-java.yml
- .pipelines/build-linux.yml
Ubuntu 18.04 is deprecated
This resolves issue https://github.com/VowpalWabbit/vowpal_wabbit/issues/4106
> ci: Upgrade Ubuntu version used in CI pipelines

- .github/workflows/dotnet_nugets.yml
With the change to the new benchmarking framework, the .NET benchmarks sometimes fail. I think it was due to this:
1. Random fluctuations in runtime crossed the 150% performance decrease threshold. Increased to 200%.
2. The workflow did not have the right permissions to create a "performance alert" PR comment. Added a permission.
> ci: Fix randomly failing .NET benchmarks

- .github/workflows/build_docs.yml
- doc/Doxyfile
This updates the doxygen CI to use a newer doxygen and removes private headers and source files from what is being parsed
> docs: only document public includes with doxygen

- test/unit_test/cb_las_spanner_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- spanner does not take into account the action that vw predicted when selecting actions that maximize volume, so we need to include it in the final non zero predictions in the case that spanner filters the vw prediction out
- adapt spanner tests to include extra prediction in the case that spanner did not select the vw predicted action
> fix: [LAS] ensure vw prediction makes it to exploration

- test/unit_test/automl_test.cc
- test/unit_test/test_common.h
- vowpalwabbit/core/include/vw/core/debug_print.h
- vowpalwabbit/core/src/merge.cc
- vowpalwabbit/core/src/reductions/search/search_meta.cc
While we still violate this in test code this fixes the issue in library code which is the most important thing.
Overloading operators in namespace `std` is not permitted. https://en.cppreference.com/w/cpp/language/extending_std
> fix: VW should not add anything to namespace std

- test/unit_test/cb_large_actions_test.cc
- test/unit_test/cb_las_one_pass_svd_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/model_weight_rand_svd_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/one_pass_svd_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/one_rank_spanner_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/spanner_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/vanilla_rand_svd_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action_space.h
- As the singular values taper off to zero then the spanner with be picking randomly from the remaining actions and in theory they are redundant, so use the number of actions that make the 99% of the sum of the singular values and select that many actions in the spanner
- this means that for a `num_actions` ~ > than the matrix rank we don't have to tune `num_actions` since results should be the same
- also make default thread pool size is ~ half the available threads (instead of `0`)
- fix some tests that were setting the test seed funny
> feat: [LAS] filter out (potentially) more actions than d based on singular values

- test/unit_test/cb_large_actions_test.cc
- test/unit_test/cb_las_one_pass_svd_test.cc
- test/unit_test/cb_las_spanner_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/one_pass_svd_impl.cc
Sparse Rademacher
also:
- fix seed setting
- add scaling in AOmega multiplication
- fix some tests
> feat: [LAS] sparse Rademacher

- test/train-sets/ref/help.stdout
- test/unit_test/cb_large_actions_test.cc
- test/unit_test/cb_las_one_pass_svd_test.cc
- test/unit_test/cb_las_spanner_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_actions_mask.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
because most things expect full predictions (python bindings / C# bindings / probably other things)
> fix: [LAS] always return full predictions

- vowpalwabbit/core/include/vw/core/array_parameters_sparse.h
This field was causing warnings and was also unused.
> refactor: remove unused field in sparse_iterator

- .github/workflows/run_benchmarks.yml
It looks like caching is not working for this job, perhaps because we are over the limit. Changing to the smaller cache strategy
> ci: change caching for benchmark job

- vowpalwabbit/core/include/vw/core/learner.h
- vowpalwabbit/core/src/reductions/conditional_contextual_bandit.cc
- vowpalwabbit/core/src/reductions/mwt.cc
- vowpalwabbit/core/src/reductions/slates.cc
- vowpalwabbit/core/src/simple_label.cc
I've gone back and forth on this one, but because of things like search and audit_regressor I think we need to leave the control with the reduction to decide if it wants to print an update.
> refactor: allow reduction to control print frequency

- test/unit_test/interactions_test.cc
- test/unit_test/parse_args_test.cc
- vowpalwabbit/core/include/vw/core/multi_model_utils.h
- vowpalwabbit/core/include/vw/core/parse_args.h
- vowpalwabbit/core/include/vw/core/parse_primitives.h
- vowpalwabbit/core/include/vw/core/parser.h
- vowpalwabbit/core/src/parse_args.cc
- vowpalwabbit/core/src/parser.cc
- vowpalwabbit/core/src/reductions/details/automl/automl_impl.cc
- vowpalwabbit/core/src/reductions/details/automl_impl.h
- Removed `using namespace` from a header
- Moved a couple of items into details namespace
- Remove unused `safe_index`
> refactor: small namespace cleanup

- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action_space.h
- vowpalwabbit/core/tests/cb_las_one_pass_svd_test.cc
When LAS is enabled then two exploration algorithms are enabled and they both call `cb_explore_adf_common`'s `persist_metrics` function which overrides the same keys
Fixed by making LAS a standalone reduction and not a cb adf common one
> fix: [LAS] LAS not a cb adf common reduction, fixes metrics with LAS bug

- vowpalwabbit/core/src/reductions/gd.cc
Previously, subtraction is done by copying weights from the newer model, and addition is done by overwriting the older weights. The results are identical, but the new implementation is more intuitive. It also makes model merging with different base models easier to implement in the future.
> refactor: implement delta add/subtract by actually adding and subtracting weights

- test/train-sets/ref/help.stdout
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/one_pass_svd_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/two_pass_svd_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action_space.h
- vowpalwabbit/core/tests/cb_las_one_pass_svd_test.cc
- vowpalwabbit/core/tests/cb_las_spanner_test.cc
- caching added also for ccb
speedup for ccb (200 actions 4 slots):
ccb with LAS with cache 13.7 ms 
ccb with LAS without cache 28.8 ms
ccb without LAS 10.3 ms
> feat: [LAS] with CCB

- vowpalwabbit/core/include/vw/core/learner.h
This is required to make the debug tree work in some very specific situations in vowpal-wabbit-next
> refactor: add api to set data object associated with learner

- demo/plt/README.md
- demo/plt/plt_demo.py
- test/train-sets/ref/plt_predict.stderr
- test/train-sets/ref/plt_predict_probabilities.stderr
- test/train-sets/ref/plt_sgd_predict.stderr
- test/train-sets/ref/plt_sgd_top1_predict.stderr
- test/train-sets/ref/plt_top1_predict.stderr
- test/train-sets/ref/plt_top1_predict_probabilities.stderr
- vowpalwabbit/core/src/reductions/plt.cc
This is a small change to PLT reduction that adds calculation of training loss also to the `predict` method when labels are available (e.g., when predicting for holdout dataset), instead of always returning 0. Which is a behavior that might cause confusion/problems to some users (as in #4511).
> feat: add a training loss calculation to the predict method of PLT reduction

- vowpalwabbit/cli/src/main.cc
In multithreaded mode, if a reduction throws an exception, it can go uncaught until the outermost catch which will cause a SIGABRT due to an unjoined thread
> fix: [parser] Fix potential crash on unjoined parser thread

- .github/workflows/dotnet_nugets.yml
- .github/workflows/native_nugets.yml
Addresses deprecations here:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> fix: deprecated github actions

- vowpalwabbit/core/include/vw/core/reductions/cb/cb_adf.h
- vowpalwabbit/core/include/vw/core/reductions/cb/cb_explore_adf_common.h
- vowpalwabbit/core/src/reductions/cb/cb_adf.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_graph_feedback.cc
- vowpalwabbit/core/tests/cb_graph_feedback_test.cc
- vowpalwabbit/core/tests/simulator.cc
- vowpalwabbit/core/tests/simulator.h
- allow multiple costs if graph feedback
> feat(CB_GF): correct update rule and simulation unit test

- wasm/test/test.js
- wasm/wasm_wrapper.cc
For the cb model, the example is not opaque but a javasctipt object that the C++ side can inspect
Moved basic vw functionality out into `vw_model_basic` class which is used as a mixin for the `vw_model` which is generic vw model implementation and the newly added `cb_vw_model`
`vw_model_basic` can be enhanced in the future with any other generic functionality
> feat: WASM initial CB model API

- .github/workflows/python_wheels.yml
fixing mistake from here: https://github.com/VowpalWabbit/vowpal_wabbit/pull/4586
'*' is not capturing branches with slashes (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)
> test: python ci on rlos PR

- .github/workflows/wasm.yml
- .gitignore
- wasm/.npmignore
- wasm/CMakeLists.txt
- wasm/README.md
- wasm/example.js
- wasm/package.json
- wasm/test/test.js
- wasm/vw.js
node can consume the modularized version that the browser plugin consumes, no need to build both
> feat: WASM packaging

- python/tests/assert_job.py
- python/tests/data_generation.py
- python/tests/pytest.json
- python/tests/test_helper.py
- python/tests/test_regression.py
> test: [RLOS_2023][WIP] updated test for regression weight 

- vowpalwabbit/core/src/reductions/gd.cc
In my testing adding this fix reduced model saving time from 9.11s to 2.08s for a 190MB model.
> perf: only format model values if writing text model

- vowpalwabbit/core/tests/cb_graph_feedback_label_parse_test.cc
- vowpalwabbit/core/tests/cb_graph_feedback_test.cc
> fix: hide graph feedback tests behind flag

- python/tests/e2e_v2/assert_job.py
- python/tests/e2e_v2/cb/data_generation.py
- python/tests/e2e_v2/cb/logging_policies.py
- python/tests/e2e_v2/cb/reward_functions.py
- python/tests/e2e_v2/cb_cont/data_generation.py
- python/tests/e2e_v2/cb_cont/logging_policies.py
- python/tests/e2e_v2/cb_cont/reward_functions.py
- python/tests/e2e_v2/classification/data_generation.py
- python/tests/e2e_v2/conftest.py
- python/tests/e2e_v2/regression/data_generation.py
- python/tests/e2e_v2/slate/action_space.py
- python/tests/e2e_v2/slate/assert_job.py
- python/tests/e2e_v2/slate/data_generation.py
- python/tests/e2e_v2/slate/logging_policies.py
- python/tests/e2e_v2/slate/reward_functions.py
- python/tests/e2e_v2/test_configs/cb.json
- python/tests/e2e_v2/test_configs/cb_cont.json
- python/tests/e2e_v2/test_configs/classification.json
- python/tests/e2e_v2/test_configs/regression.json
- python/tests/e2e_v2/test_core.py
- python/tests/e2e_v2/test_helper.py
* minor cleanup
* reduce tol for regression
> test: [RLOS2023] add datagen driver to all data stimulator

- vowpalwabbit/core/CMakeLists.txt
- vowpalwabbit/fb_parser/CMakeLists.txt
- vowpalwabbit/fb_parser/include/vw/fb_parser/parse_example_flatbuffer.h
- vowpalwabbit/fb_parser/src/parse_example_flatbuffer.cc
- vowpalwabbit/fb_parser/tests/affordance_validation_tests.cc
- vowpalwabbit/fb_parser/tests/example_data_generator.cc
- vowpalwabbit/fb_parser/tests/example_data_generator.h
- vowpalwabbit/fb_parser/tests/flatbuffer_parser_tests.cc
- vowpalwabbit/fb_parser/tests/prototype_example.h
- vowpalwabbit/fb_parser/tests/prototype_example_root.h
- vowpalwabbit/fb_parser/tests/prototype_label.cc
- vowpalwabbit/fb_parser/tests/prototype_label.h
- vowpalwabbit/fb_parser/tests/prototype_namespace.h
- vowpalwabbit/fb_parser/tests/prototype_typemappings.h
- vowpalwabbit/fb_parser/tests/read_span_tests.cc
This API will be used by consumers like RLClientLib to enable inputting FlatBuffer input.
> feat: Expose non-io_buf API for fb_parser

- vowpalwabbit/core/include/vw/core/error_data.h
- vowpalwabbit/fb_parser/include/vw/fb_parser/parse_example_flatbuffer.h
- vowpalwabbit/fb_parser/src/parse_example_flatbuffer.cc
- vowpalwabbit/fb_parser/src/parse_label.cc
- vowpalwabbit/fb_parser/tests/example_data_generator.h
- vowpalwabbit/fb_parser/tests/flatbuffer_parser_tests.cc
- vowpalwabbit/fb_parser/tests/prototype_typemappings.h
- vowpalwabbit/fb_parser/tests/read_span_tests.cc
Consumers of VW as a library can provide their own event pools, etc. Previous parsers were always able to predict when an even would be needed ahead of time, so would only allocate when necessary. This was done by relying on a single incoming event preallocation to let the external host deallocate in the case of nothing to be parsed.
This does not work for the FB parser due to how it handles re-entrancy, and we do not want to spend the time re-architecting it to avoid this. The fix, in this case, is to expand the API to include a callback to return spare events back to the host's event pool.
> feat: Support cleaning up spare examples correctly in read_span_flatbuffer()
