VowpalWabbit/vowpal_wabbit

- vowpalwabbit/lrq.cc
Seems reasonable for lrq specifications to be idempotent, and it will help with Alexander Trufanov's issue.
> idempotent lrq arguments

- vowpalwabbit/nn.cc
> multitask regularization for nn

- c_test/sample.c
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/vw_static.vcxproj
- vowpalwabbit/vwdll.h
Add missing files to static lib project
fix build errors and some warnings
> fix Visual Studio Build Errors and warning

- vowpalwabbit/cb_algs.cc
I only had to show data that was already there
>   #558 patch

- vowpalwabbit/lda_core.cc
The windows build was failing. I've put some fixes in so that it builds and removed a bunch of warnings.
Visual Studio doesn't support constexpr in VS2013
static const member doesn't work with floats
Replace it with an inline function. (Could be a macro if performance critical)
conditionally define functions which call other conditionally defined functiosn
expdigammify calls the undefined vexpdigammify
expdigammify_2 calls the undefined  vexpdigammify_2
so they aren't called when the v functions are not defined
Many case statements don't have a default case. Added one which defaults to case USE_PRECISE:
> Visual Studio doesn't support constexpr in VS2013

- vowpalwabbit/lda_core.cc
- vowpalwabbit/parse_args.cc
- vowpalwabbit/search_dep_parser.cc
- vowpalwabbit/vwdll.cpp
- vowpalwabbit/vwdll.h
Minor tweaks to MSR-annotated fixes (constexpr not supported yet, a couple of places where the SIMD code should be conditionally compiled.)
Basically, when I drop the ARM SIMD code in, shouldn't have issues related to x86-specific conditional compilation.
> simd_fixes_from_ms

- test/RunTests
- test/train-sets/ref/redefine.stderr
This PR contains additional test for recently added `--redefine` functionality.
> test --redefine functionality

- vowpalwabbit/Makefile.am
> Fix error in resolving Makefile.am conflict

- vowpalwabbit/multilabel_oaa.cc
> fix memory corruption in gcc debug builds

- R/dt2vw.R
- R/example.yaml
Added an example for the expected format of the namespaces variable.
Added the option of setting namespaces = NULL (a unique namespace containing all the variables is created).
Added an example yaml file for defining namespaces.
> R to vw data conversion

- demo/entityrelation/Makefile
Change the url of the entity relation data.
> fix the missing data error in entity relation demo

- vowpalwabbit/cb_adf.cc
@yitanms and @alekh: can you also review this?
> fixed --rank_all not being saved in the model

- vowpalwabbit/best_constant.cc
- vowpalwabbit/global_data.cc
- vowpalwabbit/global_data.h
- vowpalwabbit/lrq.cc
- vowpalwabbit/nn.cc
- vowpalwabbit/parse_args.cc
> fix tricky segfaut when using --random_seed

- demo/dependencyparsing/Makefile
Changed `ftrl` argument and removed duplicated variables.
> updated argument (#581) in demo

- Makefile.am
- vowpalwabbit/Makefile.am
- vowpalwabbit/boosting.cc
- vowpalwabbit/boosting.h
- vowpalwabbit/parse_args.cc
- vowpalwabbit/vw_static.vcxproj
Implementation of online boosting algorithms for binary classification from Beygelzimer, Kale, Luo: Optimal and adaptive algorithms for online boosting, ICML-2015.
> added boosting code

- test/train-sets/ref/lda-2pass-hang.stderr
- test/train-sets/ref/wiki1K.stderr
- vowpalwabbit/lda_core.cc
These fixed the test-mode bug but apparently changed the prediction-model values. The latter is a bigger problem based on use case. Rolling back until I can get a correct fix and validate it
> Rolling back my "fixes"

- vowpalwabbit/best_constant.cc
> loss func shouldn't be called for never observed label

- vowpalwabbit/learner.cc
refers to suggestion 3 in  https://github.com/JohnLangford/vowpal_wabbit/issues/726
> fix broken while in generic_driver

- utl/vw-doc2lda
- utl/vw-lda
'vw-lda' is a friendly higher-level wrappers which allows the users to work directly on plain-text document collections and deal with all the leg-work this entails, automatically.
This wrapper does the following:
- converts words to numeric features and numeric features back to words at the end
- allows working on many docs at a time
- support for Stop-word filtering (English only at this stage)
- more friendly options handling
- has reasonable defaults for all LDA options
- more friendly/mnemonic options with usage help
> human friendly wrappers to use lda in vw

- vowpalwabbit/interactions.h
I would like to propose this little change.
It's just a macros `INTER_WEIGHT_OP(weight1, weight2) weight1*weight2` that replaces `weight1*weight2` expressions everywhere where new feature weight is calculated for features generated by interactions.
As macros are preprocessed this shouldn't affect neither performance nor results. Regression tests shows that everything is ok.
I found out that for some tasks the ways of new feature weights calculation other than simple multiplication   may let you achieve significantly better results. Particularly `fabs(weight1-weight2)` or even `weight1>weight2?1.0:-1.0` for features generated by interacting pairs of different fund market indicators. This may be explained by that: for human traders intersection or convergence of price moving averages means …
> synthetic feature weight calculation in macros

- test/RunTests
https://github.com/JohnLangford/vowpal_wabbit/issues/745
Switch from non-portable `echo -e` to `printf`
Also fixed some indentation inconsistencies introduced recently.
> RunTests: partial fix for test failures on OS-X

- vowpalwabbit/global_data.h
- vowpalwabbit/interactions.cc
- vowpalwabbit/interactions.h
- vowpalwabbit/parse_args.cc
"Just" renaming variables, so the code is easier to read and understand.
> Cleaner code

- R/dt2vw.R
solves #761 
New features:
--> possible to process a data table with more than 100 variables
--> appends the name of a categorical variable to its value
--> possibility to write the vw data file by chuncks: added the argument append = T
> R/dt2vw.R : possible to have more than 100 variables

- cluster/Makefile
> make cluster fix

- .travis.yml
- java/src/test/java/vw/VWTest.java
Updated .travis.yml: `cd java; mvn test; cd ..` -> `cd java && mvn test && cd ..`
> Updated .travis.yml Closes #804

- .gitignore
- README.md
- utl/vw-format.pl
Few improvements on csv2vw script, packaged into a new one:
- By default outputs sparse matrix, omitting zeroes
- Ability to specify splitting column, so that several datasets are written, based on different values in that column
- Ability to specify tag and label columns
- All columns are specified with name and number (positive and negative)
- Ability to provide regex pattern for excluding certain columns
- Ability to group columns into namespaces, based on provided regex patter
> New CSV/TSV to VW format processing tool.

- test/RunTests
Small fix to the debugging (-v 4) of non-matching lines in fuzzy-compare.
> RunTests: $#w1 => $#w2 in 2nd line -v4 debug

- java/src/test/java/vw/learner/VWFloatArrayLearnerTest.java
> Validate LDA predictions vector length and make test docs more readable

- vowpalwabbit/allreduce.h
- vowpalwabbit/parse_args.cc
- vowpalwabbit/spanning_tree.cc
Conflicts:
vowpalwabbit/parse_args.cc
> fixed memory leaks

- Makefile.am
- configure.ac
- libvw.pc.in
- libvw_c_wrapper.pc.in
Add support for installing a pkg-config metadata file for VW libraries.
> Add support for pkg-config

- vowpalwabbit/multilabel.cc
Bugfix for failing to penalize for false positives.
> multilabel hamming loss bugfix

- .gitignore
- cluster/Makefile.am
- configure.ac
- explore/static/utility.h
- vowpalwabbit/gd.cc
- vowpalwabbit/log_multi.cc
- vowpalwabbit/search.cc
This is a series of patches that fixes build issues with building on 32bit platforms and out of tree builds.
> Minor build fixes

- python/sklearn_vw.py
- python/test_sklearn_vw.py
- clearing params when constructing model
- better support for sparse matrices
- fixing bug in tovw conversion for values ending in 0
- adding passes argument to constructor
> sklearn vw improvements

- vowpalwabbit/io_buf.h
- vowpalwabbit/parse_regressor.cc
> removed validate function

- vowpalwabbit/memory.h
- vowpalwabbit/parse_regressor.cc
helpful for people who might not know the connection between the -b switch and their RAM size
> more informative memory allocation failure message

- library/gd_mf_weights.cc
- vowpalwabbit/feature_group.h
- vowpalwabbit/gd.cc
- vowpalwabbit/gd_mf.cc
- vowpalwabbit/interactions.h
- vowpalwabbit/lrq.cc
- vowpalwabbit/lrqfa.cc
- vowpalwabbit/parse_example.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/search.cc
> string SSO memory problem fix

- python/sklearn_vw.py
- python/test_sklearn_vw.py
I'm gonna be pretty detailed here so you know why I did what I did.
Line 24: removed pyvw.vw as a base class of sklearn_vw.VW for two reasons. First when initializing a pipeline you have to pass in a list of estimator instances, which would actually create an instance of pyvw.vw with its arguments.  Any secondary estimators that need initial regressors will fail to initialize because the prior estimators haven't run and generated their final regressors.  So I move the pyvw.vw access into a lazy factory method that everything else calls when they need it.  Second, sklearn's grid search can run the search in parallel, but it requires the estimator be pickleable.  The VW estimator can't be pickled because pylibvw doesn't include Boost.Python pickle support. Removing pyvw.vw as a base class …
> Changes to support sklearn piplines, grid search, and estimator validation

- cs/cs/VowpalWabbitExampleCollection.cs
- cs/cs/VowpalWabbitMultiLineExampleCollection.cs
- cs/cs/VowpalWabbitSingleLineExampleCollection.cs
- cs/cs/cs.nuspec
- cs/unittest/VowpalWabbitExampleJsonValidator.cs
- vowpalwabbit/vw_dynamic.vcxproj
Added VowpalWabbitString property for single and multiline example
Added missing file to VS proj
@lhoang29 review should be quick...
> Trace improvements

- cs/unittest/RunTests.tt
> RunTests.tt hardening

- explore/cpp/MWTExplorer.h
> deleted dead bool

- python/pylibvw.cc
- python/pyvw.py
- python/sklearn_vw.py
- python/test_sklearn_vw.py
cleaning up predict call in sklearn_vw to use new predict method in pyvw
removing finish() there which causes segmentation fault when run predict, or score multiple times
added test to catch this case
> Fix for Issue 960

- README.md
I wasn't 100% sure of the code formatting convention used here, it looks like there were several variants used throughout this readme. I can update if needed.
> Add formatting to code

- vowpalwabbit/loss_functions.cc
Adds a warning for labels < 0 in poisson_loss
> label check for poisson loss

- vowpalwabbit/loss_functions.cc
The max and min are updated using labels and cause problems with non identity link functions
> Adding default limits to prediction.

- java/src/main/bin/build.sh
While trying to make a release version of VW 8.2 I noticed that the Java build script was broken.  This commit fixes that issue.
> Getting Java compilation to work

- vowpalwabbit/ect.cc
resolves https://github.com/JohnLangford/vowpal_wabbit/issues/726
Just adjust boundary of prediction-to-class interpretation. It's 0.5 for --link logistic as predictions are scaled to [0;1] and 0. for all other link functions.
> fix --ect in case --link=logistic is used

- vowpalwabbit/cost_sensitive.cc
mitigates [issue 1067](https://github.com/JohnLangford/vowpal_wabbit/issues/1067)
> A more friendly warning on csoaa bad prediction 

- python/tests/test_pyvw.py
This is just a minor change, adding a simple test for using tags in python.
Relevant issues:
- https://github.com/JohnLangford/vowpal_wabbit/issues/758
- https://github.com/JohnLangford/vowpal_wabbit/pull/1055
-Kris
> added test for tags in pyvw

- python/tests/test_sklearn_vw.py
- python/vowpalwabbit/sklearn_vw.py
> adding lrq and lrq dropout to sklearn interface

- vowpalwabbit/parse_args.cc
Hi!
This PR fixes #1164
If `--quiet` was set `--interactions` or `--cubic` weren't added to the model file
Best,
Bart
> also set all.file_options if all.quiet == true

- python/pylibvw.cc
- python/requirements.txt
- python/tests/resources/train.dat
- python/tests/test_pyvw.py
- python/tests/test_sklearn_vw.py
- python/vowpalwabbit/pyvw.py
- python/vowpalwabbit/sklearn_vw.py
For #924 
Adding ability to processes external data file with python wrapper, and save model in vw format, and support bfgs in sklearn wrapper
> Python wrapper improvements for handling external data files and model i/o

- vowpalwabbit/boosting.cc
Hi!
This PR should fix problem (2) of #1105
Best,
Bart
> Make --boosting obey --quiet

- python/README.rst
Removed incorrect closing bracket
> Adjusted brackets

- python/Makefile
needed to get correct python version includes / ldflags
> fixing typo in python makefile 

- README.md
capturing information from comments in issue #1208
> Updating readme for python installation using anaconda

- demo/recall_tree/wikipara/.gitignore
- demo/recall_tree/wikipara/DocGenerator.py
- demo/recall_tree/wikipara/Makefile
- demo/recall_tree/wikipara/README.md
- demo/recall_tree/wikipara/WikiExtractor.py
- demo/recall_tree/wikipara/makeparadata.py
> Wikiparadata

- test/daemon-test.sh
daemon-test.sh refactor, trying to fix issue https://github.com/JohnLangford/vowpal_wabbit/issues/1271
> daemon-test.sh - check status code of the netcat

- python/tests/test_sklearn_vw.py
- python/vowpalwabbit/sklearn_vw.py
added nn and related options to sklearn vw model as requested in #1232
> adding neural net options to python sklearn wrapper

- java/src/main/java/vowpalWabbit/responses/ActionProb.java
- java/src/main/java/vowpalWabbit/responses/ActionProbs.java
- java/src/main/java/vowpalWabbit/responses/ActionScore.java
- java/src/main/java/vowpalWabbit/responses/ActionScores.java
- java/src/main/java/vowpalWabbit/responses/Multilabels.java
This is a simple PR that makes all the responses Serializable on the Java side.
> Making all VW responses serializable

- java/README.md
I've added a Java README to correspond to the new Java version released (8.4.1).
> Adding Java README

- vowpalwabbit/cb_explore_adf.cc
This typo causes installation to fail from github.
>  Fix missing bracket in vw.R

- python/PACKAGE.rst
- python/setup.py
updating setup.py to support additional python3 installations (recent releases of ubuntu in particular)
also updating python packaging instructions because pypi has changed their servers
> Linux python3 setup

- demo/dbpedia/README
- demo/dbpedia/classification-example.sh
- demo/dbpedia/eval.py
This PR adds a simple end-to-end example for multi-class classification that was adapted from fastText (https://github.com/facebookresearch/fastText). 
Ran: `make && cd demo/dbpedia && ./classification-example.sh` on my macbook
> Simple multi-class classification example adapted from fastText

- cs/cli/vowpalwabbit.cpp
- cs/cli/vw_arguments.h
- cs/unittest/TestMarshalNumeric.cs
- vowpalwabbit/libvw.vcxproj
- vowpalwabbit/vw_dynamic.vcxproj
1) added parser_helper.cc to vw_dynamic project 2) migrated cli files to use vw->opt_n_args.vm instead of vw->vm 3) switched libvw win build to MultiThreadedDebugDLL to keep it compatible with other projects
> Fixed compile issues with visual studio projects/sources 

- cs/unittest/TestArguments.cs
- vowpalwabbit/parser_helper.cc
Fix unit test that checks for argument disagreement
> Throw exception when there is an argument disagreement

- vowpalwabbit/parse_args.cc
- vowpalwabbit/vwdll.cpp
- vowpalwabbit/vwdll.h
Fix for issue #1393 
Changes
1. Too many files open exception
2. Adds VW_SeedWithModel to the API
> seed with vw model

- README.md
Added documentation how to install Vowpal Wabbit Python3 integration for Debian.
> Debian python doc

- README.windows.txt
Command line tool location is specific to VS installation. Providing a generic link to determine it.
> Update Link to determine where command line tools can be found.

- python/examples/covington.py
- python/setup.py
- python/vowpalwabbit/__init__.py
- python/vowpalwabbit/pyvw.py
- python/vowpalwabbit/sklearn_vw.py
> lgtm updates to cleanup python code

- .travis.yml
- python/tests/test_sklearn_vw.py
- python/vowpalwabbit/sklearn_vw.py
- utl/vw-validate.html
Addresses #1475. 
Feedback from @Scott-Graham-Bose is welcome.
> [python] Fix shuffle between passes and add a test for it

- utl/vw-varinfo
https://github.com/JohnLangford/vowpal_wabbit/issues/1547
> utl/vw-varinfo: work-around for issue/1547:

- README.windows.txt
Added instructions to build Vowpal Wabbit in VS2015 on win10.
> Update Windows README

- reinforcement_learning/unit_test/eventhub_client_test.cc
- reinforcement_learning/unit_test/http_server/http_server.h
- reinforcement_learning/unit_test/live_model_test.cc
- reinforcement_learning/unit_test/model_mgmt_test.cc
Not fix yet, but error message improvement.
> rl client tests fix

- reinforcement_learning/doc/mainpage.dox
- reinforcement_learning/doc/python.dox
- reinforcement_learning/examples/python/basic_usage.py
- reinforcement_learning/include/live_model.h
- reinforcement_learning/include/ranking_response.h
- Improve wording in documentation for clarity
- Remove period from params
- Fix context json in python basic example
- White space fixes
> Reinforcement_learning documentation updates + python example context json fix

- reinforcement_learning/rlclientlib/live_model_impl.cc
Sending observations to observation eventhub and interactions to the interaction one.
> loggers initialization fix

- reinforcement_learning/bindings/python/py_api.cc
- reinforcement_learning/bindings/python/setup.py
Forgotten trace-related changes.
> rl python bindings fix

- reinforcement_learning/rlclientlib/live_model_impl.cc
- reinforcement_learning/rlclientlib/vw_model/vw_model.cc
choose_rank() was returning chosen_action_index instead of chosen_action.
> Bug Fix: chosen_action_index was returned instead of chosen_action.

- vowpalwabbit/parse_example.cc
> Use cerr for parser warnings

- cs/cli/vw_base.cpp
- cs/test/Program.cs
- java/src/main/java/vowpalWabbit/learner/VWLearners.java
- python/pylibvw.cc
- vowpalwabbit/main.cc
> Disable stdin processing for all but single instance CLI. Fixes #1300

- .scripts/package.cmd
- .scripts/test.cmd
- cs/cs/cs.nuspec
- cs/cs_json/cs_json.nuspec
- cs/cs_parallel/cs_parallel.nuspec
* Creates a test script to run C smoke tests, C++ unit tests and C# UTs
* Creates a package script to generate NuGet packages
* Updates the nuspec files to properly support injecting paths into them
Note: The test script is currently designed to be used by humans, and it
may fail to error out a CI/CD process that simply executes the script.
> Scripts for running tests and generating NuGet packages

- CMakeLists.txt
- vowpalwabbit/CMakeLists.txt
> Fix static linking for Ubuntu

- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_example_json.h
- vowpalwabbit/parser.cc
- vowpalwabbit/parser.h
- Allows for reduction override of Json parser. Required for CCB
- Improves memory management of json_parser object through type erased shared_ptr deletion on destruction
> Type erase json parser context for easier deletion

- vowpalwabbit/label_dictionary.cc
- vowpalwabbit/label_dictionary.h
This caused problems when the api was used with namespaces >127
> Fix usage of char instead of unsigned char for namespace index

- python/vowpalwabbit/pyvw.py
In #1809 a bug was introduced which meant the raw_example constructor was always used, this fixes that regression.
> Fix Python example constructor overloading

- vowpalwabbit/cb_explore_adf.cc
- vowpalwabbit/parser.cc
> Clear cb labels when returning to pool

- vowpalwabbit/conditional_contextual_bandit.cc
This fixes an issue where ccb wasn't learning due to not constructing the cb examples correctly
> [CCB] Fix for learning 

- test/RunTests
- test/train-sets/ref/holdout_after.stderr
- test/train-sets/ref/holdout_after_2passes.stderr
- vowpalwabbit/parser.cc
> Fix counting issue with --holdout_after option

- vowpalwabbit/confidence.cc
> fix for no label confidence

- .scripts/build.cmd
- appveyor.yml
Test to see if this improves the warning visibility in AppVeyor.
Related: https://github.com/VowpalWabbit/vowpal_wabbit/issues/1820
> Use Appveyor MSBuildLogger

- test/negative-test.sh
- test/train-sets/ref/malformed-onethread-strict_parse.stderr
- test/train-sets/ref/malformed-strict_parse.stderr
- vowpalwabbit/main.cc
- vowpalwabbit/parse_dispatch_loop.h
- vowpalwabbit/parse_example.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/vw_exception.h
I realized that the rethrowing is necessary since it occurs on the parse thread, and so to make it to the main thread and exit in that same way then we stash+rethrow.
Note: this is merging into optional_exception, then you can merge that one.
> Update to vw_exception

- test/save_resume_test.py
- vowpalwabbit/ftrl.cc
- vowpalwabbit/gd.cc
- vowpalwabbit/gd.h
Reverts VowpalWabbit/vowpal_wabbit#1912
> Revert "Fix to save the state of FTRL models"

- test/daemon-test.sh
> fix for daemon race condition

- vowpalwabbit/cb_explore_adf.cc
> change semantics of lambda

- vowpalwabbit/cb_explore_adf.cc
This avoids a misconfiguration of a reduction.
> Fix misconfiguration

- vowpalwabbit/cb.cc
- vowpalwabbit/cb_explore_adf.cc
> Fix clear labels the correct way

- cs/examples/simulator/Program.cs
- cs/examples/simulator/VowpalWabbitSimulator.cs
Updated simulator to code used for 10actions x 10contexts simulations
Cosmetic changes and minor improvements
> CS simulator v3.0

- vowpalwabbit/cb_explore_adf.cc
> Fix predict path for cb_explore_adf First

- vowpalwabbit/ccb_label.cc
- vowpalwabbit/conditional_contextual_bandit.cc
- vowpalwabbit/object_pool.h
- vowpalwabbit/v_array_pool.h
> Reuse memory in ccb rather than alloc/dealloc

- vowpalwabbit/cb_adf.cc
- vowpalwabbit/cb_adf.h
- vowpalwabbit/cb_explore_adf.cc
- vowpalwabbit/cb_explore_adf.h
- vowpalwabbit/explore_eval.cc
- vowpalwabbit/gen_cs_example.cc
> cb_explore_adf: fixed bug when resetting cb_type + improvements

- MANIFEST.in
> Add LICENSE to the python source package

- vowpalwabbit/vw_exception.h
- vowpalwabbit/vw_types.natvis
- Add `DBG` macro for easy print debugging
- Add `dense_parameters` natvis type so we can inspect in VS debugger
> DBG macro and dense_parameters natvis definition

- vowpalwabbit/cb_explore_adf_bag.cc
- vowpalwabbit/cb_explore_adf_common.h
- vowpalwabbit/cb_explore_adf_cover.cc
- vowpalwabbit/cb_explore_adf_first.cc
- vowpalwabbit/cb_explore_adf_greedy.cc
- vowpalwabbit/cb_explore_adf_regcb.cc
- vowpalwabbit/cb_explore_adf_softmax.cc
The bug was caused by uninitialized variables in the setup
Fixes #2099
> Cb explore adf initialize vars

- vowpalwabbit/cb_adf.cc
- vowpalwabbit/cb_adf.h
- vowpalwabbit/cb_explore_adf_common.h
- vowpalwabbit/conditional_contextual_bandit.cc
- vowpalwabbit/explore_eval.cc
- strip vw* all reference from cb_adf
- related: https://github.com/VowpalWabbit/vowpal_wabbit/issues/2002
> Refactor cb_adf reduction

- vowpalwabbit/global_data.cc
- vowpalwabbit/vw_core.vcxproj
- Also add missing header file to .vcxproj file
> Use numeric_limits

- vowpalwabbit/vw_types.natvis
Allows visual studio debugger to display capacity of v_array
> Add capacity to v_array natvis definition

- vowpalwabbit/global_data.cc
- vowpalwabbit/parse_args.cc
> Fix segfault when ring_size argument is not supplied

- python/pylibvw.cc
> Add deleter for parsed examples

- vowpalwabbit/cb_sample.cc
> Disallow combining no_sample and cb_sample

- library/libsearch.h
- library/search_generate.cc
- python/pylibvw.cc
- vowpalwabbit/array_parameters.h
- vowpalwabbit/main.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/search.cc
- vowpalwabbit/vw_exception.cc
> Unify throwing of exceptions to use vw_exception instead of bare std::exception

- python/examples/Learning_to_Search.ipynb
Learn2Search's invalid JSON fix
> Learning2Search notebook format fix

- vowpalwabbit/main.cc
`get_argv_from_string` is deprecated, replace the usage
> Fix deprecated function usage, add file opened check

- .travis.yml
Updated Travis CI image with following change: https://github.com/VowpalWabbit/docker-images/commit/0575e82544d8e1beb105b0fd22826d3f0e985476
> Update .travis.yml to fix Maven issue

- python/tests/test_pyvw.py
- python/vowpalwabbit/pyvw.py
> Fix str function in cbandit to produce correct format

- test/RunTests
Quick follow up to fix issue in #2315
> Need to decrement failure count in case of expected failure in RunTests

- vowpalwabbit/cb_explore.cc
- vowpalwabbit/cb_explore_adf_first.cc
- vowpalwabbit/cb_explore_adf_greedy.cc
- vowpalwabbit/cb_explore_adf_softmax.cc
Fix the issue #2322 .
Implements producing an error for epsilon passed not in the range [0,1].
> Fix the issue #2322 to throw error for invalid epsilon argument passed.

- vowpalwabbit/decision_scores.cc
- vowpalwabbit/decision_scores.h
- vowpalwabbit/slates.cc
Change estimator portion of output to use clearer implementation of PI
> [Slates] Slates PI estimator

- .github/ISSUE_TEMPLATE/config.yml
> Fix malformed yml

- test/unit_test/slates_test.cc
- vowpalwabbit/scope_exit.h
- Fix init order warning
- Fix unused variable warning
> Fix warnings in unit test project

- test/unit_test/CMakeLists.txt
- test/unit_test/initialize_test.cc
- test/unit_test/unit_test.vcxproj
- test/unit_test/unit_test.vcxproj.filters
- vowpalwabbit/parse_args.cc
> Revert API break

- vowpalwabbit/parser.cc
> Drain the queue if it is non empty due to possible early termination exits

- vowpalwabbit/bfgs.cc
`ftime` is deprecated. All usages are replace with std::chrono C++ APIs.
> Switch to std::chrono in bfgs to fix deprecated warnings

- python/vowpalwabbit/sklearn_vw.py
Caught in review: https://github.com/VowpalWabbit/vowpal_wabbit/pull/2368#discussion_r445120526
> Revert doc comment change in #2368

- cs/unittest/RunTests.tt
- test/RunTests
- test/daemon-test.sh
- vowpalwabbit/parser.cc
Resolves #2509 
Aiming to consistently set the reader across `parser.cc` as it was being set in various places resulting `--json` to be ignored when using `--daemon`
> Set reader consistently

- cs/test/Program.cs
- cs/unittest/TestJsonDict.cs
Disabling `TestJsonDictClass` as it fails randomly. Issue: #2527
> Disable flaky test

- python/pylibvw.cc
- vowpalwabbit/CMakeLists.txt
- vowpalwabbit/global_data.cc
- vowpalwabbit/global_data.h
- vowpalwabbit/kskip_ngram_transformer.cc
- vowpalwabbit/kskip_ngram_transformer.h
- vowpalwabbit/parse_args.cc
- vowpalwabbit/parse_regressor.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/parser.h
- vowpalwabbit/vw_core.vcxproj
Encapsulates ngram creation and application. Removes several fields from all and parser
> Extract ngram creation and transformation to a separate class

- .github/workflows/format_check.yml
- Provide guidance about how to fix
- Change to triple dot notation for diff
> Make code formatting check easier to fix

- explore/CMakeLists.txt
- vowpalwabbit/slim/include/example_predict_builder.h
- vowpalwabbit/slim/src/CMakeLists.txt
> VWSlim fixes

- vowpalwabbit/conditional_contextual_bandit.cc
> Ensure CCB labels are restored if an exception is throw. Add temporary logging so we can validate the fix.

- vowpalwabbit/log_multi.cc
this thing has been there for 2 years apparently
> [log_multi] remove extra arg

- python/tests/test_cb.py
adding this test based on the 'getting started' example we have on python.
there's a reported seg fault based on issue #2605
> [py] add test based on example

- .github/workflows/run_benchmarks.yml
- test/benchmarks/input_format_benchmarks.cc
and simple example parsing/re-use example with label
> benchmark against master

- .github/workflows/build_docs.yml
- .github/workflows/upload_coverage.yml
- .pipelines/build-linux-java.yml
- .pipelines/build-linux-valgrind.yml
- .pipelines/build-linux.yml
- setup.py
Pulling this out of the flatbuffer PR
> update builds to point to latest vw image

- .github/workflows/build_docs.yml
> Fix upload docs pipeline

- cs/unittest/RunTests.tt
- test/RunTests
- test/train-sets/cb_as_ccb.json
- test/train-sets/ref/cb_as_ccb.stderr
- test/unit_test/dsjson_parser_test.cc
- test/unit_test/json_parser_test.cc
- vowpalwabbit/parse_example_json.h
> CB-as-CCB action indexing fix

- test/unit_test/ccb_parser_test.cc
- test/unit_test/continuous_actions_parser_test.cc
- test/unit_test/json_parser_test.cc
- test/unit_test/multiclass_label_parser_test.cc
- test/unit_test/slates_parser_test.cc
- vowpalwabbit/cb.cc
- vowpalwabbit/cb_continuous_label.cc
- vowpalwabbit/ccb_label.cc
- vowpalwabbit/cost_sensitive.cc
- vowpalwabbit/label_parser.h
- vowpalwabbit/multiclass.cc
- vowpalwabbit/multilabel.cc
- vowpalwabbit/no_label.cc
- vowpalwabbit/parse_example.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/simple_label.cc
- vowpalwabbit/slates_label.cc
will need to parse prediction hints for CATS (for txt labels)
> Pass reduction features to label parsers

- test/unit_test/continuous_actions_parser_test.cc
- vowpalwabbit/cb_continuous_label.cc
- vowpalwabbit/constant.h
- vowpalwabbit/continuous_actions_reduction_features.h
- vowpalwabbit/parse_example_json.h
- vowpalwabbit/prob_dist_cont.cc
- vowpalwabbit/prob_dist_cont.h
Parse CATS text label and get pdf hint
> Cats pdf hint in text

- utl/flatbuffer/vw_to_flat.cc
- utl/flatbuffer/vw_to_flat.h
- vowpalwabbit/parser/flatbuffer/parse_label.cc
- vowpalwabbit/search.cc
- vowpalwabbit/search.h
- vowpalwabbit/search_dep_parser.cc
- vowpalwabbit/search_graph.cc
Found while trying to run all of RunTests for flatbuffers plus some tidying up
> Fix some flatbuffer bugs

- cs/unittest/TestTracing.cs
- vowpalwabbit/main.cc
- vowpalwabbit/parse_args.cc
At least when using the python vw api, the progressive validation header does not print. This will fix it.
> Fix missing progressive validation header

- test/train-sets/ccb_test_interactions.dat
- test/train-sets/ref/ccb_test_interactions.stderr
- vowpalwabbit/interactions_predict.h
Use correct loop variable in interactions
> fix invert hash for interactions

- test/unit_test/CMakeLists.txt
- test/unit_test/unit_test.vcxproj
- test/unit_test/vw_versions_test.cc
this test is going to fail because we used 10 which is being compared as 1
> [test] add vw version test

- vowpalwabbit/v_array.h
This will not pass CI, the purpose is to review small changes visually until we get to a point where we are back to working end to end.
> [v_array] Give v_array constructor, destructor, copy and move special functions

- vowpalwabbit/ccb_label.h
- vowpalwabbit/ccb_reduction_features.h
- vowpalwabbit/conditional_contextual_bandit.cc
- vowpalwabbit/object_pool.h
- vowpalwabbit/v_array_pool.h
Main change here is the value based object pool has changed to being rvalue based. Thanks @olgavrou for your help on that
> [v_array] CCB v_array fixes

- vowpalwabbit/conditional_contextual_bandit.cc
- vowpalwabbit/conditional_contextual_bandit.h
- vowpalwabbit/parser.cc
> Check for newline in parser properly when ccb

- vowpalwabbit/v_array.h
Migrated from @peterychang's work here: https://github.com/peterychang/vowpal_wabbit/pull/2
> Add reserve, resize_actual, make erase_count private

- vowpalwabbit/cbify.cc
- vowpalwabbit/cbify.h
Prompted by https://github.com/VowpalWabbit/vowpal_wabbit/pull/2680
cbify_adf_data can be reused completely and we just need the convenience of all the related functions in the same place.
> [cbify] cbify_adf_data refactor

- vowpalwabbit/cb_algs.cc
- vowpalwabbit/cb_algs.h
- vowpalwabbit/cb_explore.cc
- vowpalwabbit/cb_explore.h
Prompted by https://github.com/VowpalWabbit/vowpal_wabbit/pull/2680
> [cb, cb_explore] small refactor for reuse

- test/run_tests.py
- utl/flatbuffer/vw_to_flat.cc
- vowpalwabbit/parser/flatbuffer/parse_label.cc
- vowpalwabbit/parser/flatbuffer/schema/example.fbs
> [Flatbuffers] add initial field to simple label (and enable --nn test)

- vowpalwabbit/baseline.cc
- vowpalwabbit/cbify.cc
- vowpalwabbit/example.cc
- vowpalwabbit/example.h
- vowpalwabbit/example_predict.cc
- vowpalwabbit/example_predict.h
- vowpalwabbit/expreplay.h
- vowpalwabbit/ezexample.h
- vowpalwabbit/memory_tree.cc
- vowpalwabbit/search.cc
- vowpalwabbit/search_entityrelationtask.cc
- vowpalwabbit/search_sequencetask.cc
- vowpalwabbit/vw.h
- vowpalwabbit/warm_cb.cc
Reverts VowpalWabbit/vowpal_wabbit#2906
> Revert "Migrate example copying to `clone` function and deprecate old methods"

- test/benchmarks/input_format_benchmarks.cc
- test/benchmarks/rcv1_benchmarks.cc
- vowpalwabbit/allreduce.h
- vowpalwabbit/allreduce_threads.cc
- vowpalwabbit/cache.cc
- vowpalwabbit/parser.cc
- vowpalwabbit/parser.h
> refactor: Reduce number of raw pointers

- .github/workflows/build_python_wheels.yml
- .github/workflows/build_python_wheels_macos.yml
- .github/workflows/build_python_wheels_windows.yml
- .github/workflows/build_vw_slim.yml
- .github/workflows/build_windows_cmake.yml
- .github/workflows/format_check.yml
- .github/workflows/run_benchmarks.yml
- .github/workflows/upload_coverage.yml
Add a pattern that allows us to run CI for patch release branches
> ci: run CI on release branches

- cs/cli/vw_prediction.cpp
- cs/cli/vw_prediction.h
> feat: Add active multiclass to C# API

- .github/workflows/build_python_wheels.yml
- .github/workflows/build_python_wheels_macos.yml
- .github/workflows/build_python_wheels_windows.yml
- .github/workflows/build_vw_slim.yml
- .github/workflows/build_windows_cmake.yml
- .github/workflows/format_check.yml
- .github/workflows/run_benchmarks.yml
- .github/workflows/upload_coverage.yml
- .pipelines/build-linux-java.yml
- .pipelines/build-linux-valgrind.yml
- .pipelines/build-linux.yml
- .pipelines/build-macos.yml
- .pipelines/build-windows-nuget.yml
- Only run slow CIs when relevant paths change and 
- Only build master and release push based triggers
> ci: Reduce CI burden

- ext_libs/ext_libs.cmake
- vowpalwabbit/CMakeLists.txt
This MR fixes:
- build with external RapidJSON library
- cmake install target
> fix: cmake build

- python/tests/test_tutorial.py
this test was adapted from this tutorial: https://vowpalwabbit.org/tutorials/cb_simulation.html
> test: add cb simulation tutorial as test

- setup.py
* Enables user-supplied CMake generator --global-option
* Updates setup script to use Python setuptools to discover headers
> build: Enable building Python library using VS2019

- vowpalwabbit/binary.cc
- vowpalwabbit/learner.h
some formatting got added in learner
> feat: add learner builder for no-data learners

- .github/workflows/build_windows_cmake.yml
Copied from https://github.com/VowpalWabbit/vowpal_wabbit/pull/3184
but for windows cmake only CI job.
> ci: Fix Windows CI issue

- vowpalwabbit/cb_dro.cc
> fix: use reference for pred local variable in cb_dro

- vowpalwabbit/active.cc
This is highly whitespace dependent - reverting changes in #3243
> fix: undo active printing change

- vowpalwabbit/active.cc
> fix: add back setting active property in reduction setup

- python/pylibvw.cc
Added in response to a question on Gitter
> feat: expose holdout sum loss in python bindings

- test/train-sets/ref/help.stdout
- test/train-sets/ref/help_cbadf.stdout
- vowpalwabbit/gd.cc
> docs: update help strings in gd

- test/core.vwtest.json
- test/train-sets/ref/cb_simple_pdrop.stderr
- test/train-sets/ref/ccb_simple_pdrop.stderr
- vowpalwabbit/cb_explore_adf_common.h
- vowpalwabbit/conditional_contextual_bandit.cc
Incorporating weight into average loss numerator
Fixes #3056
> fix: cb/ccb loss fix

- vowpalwabbit/bfgs.cc
- vowpalwabbit/global_data.cc
- vowpalwabbit/global_data.h
- Rather than unrecognized option it will say options depend on bfgs once other dependent option PR is merged
- Removes hession_on from all
> feat: better error message for bfgs dependent options

- vowpalwabbit/cats_tree.cc
> fix: cats_tree bandwidth overflow, Resolves: #3542

- test/core.vwtest.json
- test/train-sets/ref/marginal_invert_hash_readable_model.txt
- vowpalwabbit/marginal.cc
> fix: marginal --invert_hash feature names

- python/vowpalwabbit/pyvw.py
args and kwargs were not working with the original system
Next: https://github.com/VowpalWabbit/vowpal_wabbit/compare/master...jackgerrits:jagerrit/more_renames_python?expand=1
> fix: fix __init__ args for deprecated classes

- test/train-sets/ref/automl_readable.txt
- vowpalwabbit/automl.cc
- vowpalwabbit/automl.h
- vowpalwabbit/boosting.cc
- vowpalwabbit/ccb_label.h
- vowpalwabbit/ccb_reduction_features.h
- vowpalwabbit/slates_label.h
Intentionally tests against old version for this PR.
Should fix build issues in #3667
> fix: fix compile issues when consuming fmt 8.1.1

- test/unit_test/CMakeLists.txt
- test/unit_test/text_utils_test.cc
- test/unit_test/unit_test.vcxproj
- test/unit_test/unit_test.vcxproj.filters
- vowpalwabbit/text_utils.cc
- vowpalwabbit/text_utils.h
Function will be used for help string generation
> feat: add text wrap function

- test/train-sets/ref/help.stdout
- vowpalwabbit/reductions/cb/cb_explore.cc
> feat: remove extra allocations, add pred/lbl types to cb_explore

- python/tests/test_pyvw.py
- python/vowpalwabbit/pyvw.py
> fix: fix splitting on double spaces in pyvw __init__

- test/unit_test/automl_weights_test.cc
closes https://github.com/VowpalWabbit/vowpal_wabbit/issues/3767
> fix: use are_same instead of are_same_rel

- test/run_tests.py
> test: compare json key-wise as opposed to as text in run_tests.py

- test/unit_test/loss_functions_test.cc
- vowpalwabbit/loss_functions.cc
- Added test cases for the expectile loss function in loss_functions_tests.cc
- Modified the multiplication by the expectile parameter in loss_functions.cc
> test: added expectile loss function unit tests

- python/vowpalwabbit/dftovw.py
CC @etiennekintzler 
Addressed feedback: https://github.com/VowpalWabbit/vowpal_wabbit/pull/3875#discussion_r851613984
> refactor: address follow up comment for from_column_names

- .vscode/settings.json
- python/vowpalwabbit/pyvw.py
- vowpalwabbit/core/include/vw/core/action_score.h
- vowpalwabbit/core/include/vw/core/learner.h
- vowpalwabbit/core/include/vw/core/parse_primitives.h
- vowpalwabbit/core/include/vw/core/vw_string_view_fmt.h
- vowpalwabbit/core/src/action_score.cc
> refactor: Bump fmt and spdlog versions

- test/benchmarks/standalone/benchmark_text_input.cc
- test/unit_test/cb_large_actions_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action_space.h
SVD on A * A.transpose() (AAtop for short)
AAtop will be KxK and PSD
still experimenting with this approach
> feat: [las] AAtop different approach to las SVD step

- test/benchmarks/standalone/benchmark_text_input.cc
- test/unit_test/cb_large_actions_test.cc
- vowpalwabbit/core/include/vw/core/qr_decomposition.h
- vowpalwabbit/core/src/qr_decomposition.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action_space.h
experimenting with this implementation
added unit test for it `test_two_Ys_are_equal`
> feat: [las] Y matrix stored in a vw model array

- vowpalwabbit/core/src/cb_continuous_label.cc
- vowpalwabbit/core/src/multilabel.cc
- vowpalwabbit/core/src/slates_label.cc
resolves https://github.com/VowpalWabbit/vowpal_wabbit/issues/4055
> fix: clear before reading label cache

- test/unit_test/automl_test.cc
- vowpalwabbit/core/src/reductions/automl.cc
- vowpalwabbit/core/src/reductions/details/automl/automl_impl.cc
- vowpalwabbit/core/src/reductions/details/automl/automl_iomodel.cc
- vowpalwabbit/core/src/reductions/details/automl/automl_oracle.cc
- vowpalwabbit/core/src/reductions/details/automl/automl_util.cc
- vowpalwabbit/core/src/reductions/details/automl_impl.h
Also some smaller related refactors
> refactor: [automl] prepare aml_estimator for other estimator impl

- test/unit_test/cb_large_actions_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/one_pass_svd_impl.cc
and make one_pass default
Speedup achieved: 30-60% depending on the payload (300 actions - 1k actions)
> perf: [LAS] speedup by removing branch from hot path

- test/unit_test/cb_large_actions_test.cc
- test/unit_test/cb_las_one_pass_svd_test.cc
- test/unit_test/cb_las_spanner_test.cc
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/model_weight_rand_svd_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/one_pass_svd_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/one_rank_spanner_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/spanner_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action/vanilla_rand_svd_impl.cc
- vowpalwabbit/core/src/reductions/cb/details/large_action_space.h
resolve warnings and fix some naming
> chore: [LAS] code cleanup

- .github/workflows/asan.yml
Test 67 failure fixed in https://github.com/VowpalWabbit/vowpal_wabbit/pull/4167
> ci: Enable test 67 with ASan

- .github/workflows/dotnet_nugets.yml
- nuget/dotnet/dotnet.nuspec.in
- nuget/dotnet/dotnetcore.nuspec.in
> fix: Add native runtime dependencies to nuspec

- test/run_tests_model_gen_and_load.py
and pass arguments to function calls
> fix: [CI] check for missing args consistently in forwards/backwards compat

- vowpalwabbit/core/CMakeLists.txt
- vowpalwabbit/core/include/vw/core/model_utils.h
- vowpalwabbit/core/tests/model_util_test.cc
> feat: add unique_ptr support to model_utils

- python/vowpalwabbit/sklearn.py
Numpy 1.24 removed these deprecated type aliases.
> fix: remove type numpy aliases as they are now removed upstream

- vowpalwabbit/core/include/vw/core/learner.h
- vowpalwabbit/core/src/reductions/automl.cc
> refactor: migrate automl finish_example

- python/docs/source/tutorials/python_cats.ipynb
it is not a step function as claimed by commit fb7ae49
> revert: previous wrong correction in docs

- python/docs/source/tutorials/cmd_linear_regression.md
- python/docs/source/tutorials/python_classification.ipynb
> docs: minor tutorial cleanups

- vowpalwabbit/cli/src/main.cc
- vowpalwabbit/core/include/vw/core/global_data.h
- vowpalwabbit/core/include/vw/core/vw.h
- vowpalwabbit/core/src/global_data.cc
- vowpalwabbit/core/src/vw.cc
Essentially a revert back to old naming.
> refactor: rename finalize_driver to finish

- test/train-sets/ref/coin_model_overflow.invert.txt
- vowpalwabbit/core/src/reductions/gd.cc
> fix: invert_hash for coin/ftrl

- python/vowpalwabbit/dftovw.py
> fix: Account for | in make_valid_name()

- python/pylibvw.cc
- python/tests/test_pyvw.py
- python/vowpalwabbit/pyvw.py
https://github.com/VowpalWabbit/vowpal_wabbit/issues/4478
Breaks python api of push_feature_list() and push_feature_dict() since the args change
> fix!: [py] use full word for namespace and add test

- test/core.vwtest.json
- test/train-sets/ref/las_egreedy_ips.stderr
- vowpalwabbit/core/src/reductions/cb/cb_explore_adf_large_action_space.cc
It is a remnant of squarecb only with LAS
> chore: [LAS] don't force mtr with LAS

- vowpalwabbit/core/include/vw/core/parse_example_json.h
- vowpalwabbit/core/include/vw/core/parse_slates_example_json.h
- vowpalwabbit/core/src/parse_example_json.cc
- vowpalwabbit/core/src/parse_slates_example_json.cc
- vowpalwabbit/json_parser/include/vw/json_parser/parse_example_json.h
- vowpalwabbit/json_parser/include/vw/json_parser/parse_example_slates_json.h
- vowpalwabbit/json_parser/src/parse_example_json.cc
- vowpalwabbit/json_parser/src/parse_example_slates_json.cc
**NOTE: will need to update to const in rlclientlib for new release**
> refactor: dedup dict const

- python/vowpalwabbit/pyvw.py
> fix: fix multiline typo

- .github/workflows/wasm.yml
- wasm/example.js
- wasm/test/test.js
- wasm/vw.js
- wasm/wasm_wrapper.cc
- also added save load
- PR was getting big so thought I'd stop here
> feat: WASM VW JS wrapper file/classes

- .github/workflows/python_wheels.yml
Turning python tests ci for feature branch
> test: turn on tests for rlos2023
